<?php
  include  VIEW.'layouts'.DIRECTORY_SEPARATOR.'header.phtml';
  ?>

<body>

  <!-- start pages photo -->
  <section class="cover-background top-space" style="background-image:url('/images/home/wbg.jpg')">
        <div class="opacity-medium bg-purple"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12 display-table page-title">
                    <div class="vertical-align-middle text-center">
                        <!-- start sub title -->
                        <h1 class="text-white text-shadow-black">About US</h1>
                        <!-- end sub title -->
                        <!-- start page title -->
                        <!-- <h1 class="text-white text-shadow-black"><?php echo $lang['item31']?></h1> -->
                        <!-- end page title -->
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- end pages photo - -->


  

<!-- service start -->
<section id="numone" class="wow fadeIn p-section" style="visibility: visible; animation-name: fadeIn; 
    background-color: #f9f9f9;">
 
    <div class="container">
        <div class="row mb-80px">
            <!-- start feature box item -->
            <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 feature-box-1 xs-margin-30px-bottom wow fadeIn last-paragraph-no-margin" style="visibility: visible; animation-name: fadeIn;">
                <div class="col-md-12 col-sm-12 no-padding margin-15px-bottom alt-font text-center">
                    <h3 class="text-blue letter-spacing-minus-1 font-weight-600 servic-num"><i class="fas fa-phone text-orange"></i></h3>
                    <p class="text-large text-extra-dark-gray line-height-22 padding-20px-left sm-padding-15px width-100 vertical-align-middle text-size-20px">+967 777222333</p>
                </div>
                <!-- <p class="width-90 sm-width-100 text-center font-14"></p> -->
            </div>
            <!-- end feature box item -->
            <!-- start feature box item -->
            <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 feature-box-1 xs-margin-30px-bottom wow fadeIn last-paragraph-no-margin" data-wow-delay="0.2s" style="visibility: visible; animation-delay: 0.2s; animation-name: fadeIn;">
                <div class="col-md-12 col-sm-12 no-padding margin-15px-bottom alt-font text-center">
                    <h3 class="text-blue letter-spacing-minus-1 font-weight-600 servic-num"><i class="fas fa-map-marker-alt text-orange"></i></h3>
                    <p class="text-large text-extra-dark-gray line-height-22 padding-20px-left width-100 vertical-align-middle text-size-20px">Sana'a Yemen </p>
                </div>
                <!-- <p class="width-90 sm-width-100 text-center font-14">Contact us with your questions and we’ll answer, day or night.</p> -->
            </div>
            <!-- end feature box item -->
            <!-- start feature box item -->
            <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 feature-box-1 wow fadeIn last-paragraph-no-margin" data-wow-delay="0.4s" style="visibility: visible; animation-delay: 0.4s; animation-name: fadeIn;">
                <div class="col-md-12 col-sm-12 no-padding margin-15px-bottom alt-font text-center">
                    <h3 class="text-blue letter-spacing-minus-1 font-weight-600 servic-num"><i class="fas fa-envelope text-orange"></i></h3>
                    <p class="text-large text-extra-dark-gray line-height-22 padding-20px-left width-100 vertical-align-middle text-size-20px">fundme849@gmail.com</p>
                </div>
                <!-- <p class="width-90 sm-width-100 text-center font-14">Lorem Ipsum is simply dummy text of the printing and typesetting.</p> -->
            </div>
            <!-- end feature box item -->
        </div>
    </div>
</section>
<!-- service start -->
<div class="container" style="visibility: visible; animation-name: fadeIn;">
        <div class="row mb-80px">
            <!-- start feature box item -->
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 feature-box-1 xs-margin-30px-bottom wow fadeIn last-paragraph-no-margin" style="visibility: visible; animation-name: fadeIn;">
              <img src="/images/home/1(7).jpg" alt="" width="500" srcset="">
            </div>
                <div class="col-lg-6 col-md-6 col-sm-12 no-padding margin-15px-bottom alt-font text-center">
                    <p class="text-large text-extra-dark-gray line-height-22 padding-20px-left sm-padding-15px width-100 vertical-align-middle text-size-20px margin-t-90">Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores sed numquam adipisci non reprehenderit debitis est, inventore ratione hic, iusto cupiditate aut rerum nam corrupti excepturi beatae deserunt eius facilis?</p>
                </div>
                <!-- <p class="width-90 sm-width-100 text-center font-14"></p> -->
            </div>
         
            
           
        </div>
    </div>

    <?php include  VIEW.'layouts'.DIRECTORY_SEPARATOR.'footer_section.phtml'; ?>
    <?php include  VIEW.'layouts'.DIRECTORY_SEPARATOR.'footer.phtml'; ?>

