<?php

// include  VIEW.'layouts'.DIRECTORY_SEPARATOR.'head.phtml';
include  VIEW.'layouts'.DIRECTORY_SEPARATOR.'header.phtml'; ?>

<body>

  <!-- start pages photo -->
  <section class="cover-background top-space" style="background-image:url('/images/1(1).jpg');">
        <div class="opacity-medium bg-dark"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12 display-table page-title">
                    <div class="vertical-align-middle text-center">
                        <!-- start sub title -->
                        <span class="text-white text-shadow-black">Add Compigan</span>
                        <!-- end sub title -->
                        <!-- start page title -->
                        <h1 class="text-white text-shadow-black">Welcome to My Compigans</h1>
                        <!-- end page title -->
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- end pages photo - -->


  <!-- profile page start-->
  <!-- <div class="main main-raised border-50 shadow-div col-md-12"> -->
	<section>
			<div class="container register">
					<div class="row">
						<div class="col-md-12 register-right shadow-div">

							<div class="tab-content" id="myTabContent">
								<div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
									<h3 class="register-heading">Add Your Compagin</h3>
									<div class="row register-form wow fadeIn">
                  <form class="col-md-12" action="" name="addCompign" id="addCompign" method="post" enctype="multipart/form-data">
										<div>
											<div class="form-group">
												<label for="Title" class="laple-forms">Title </label>
												<input type="text" id="Title" oninput="stringlength(document.addCompign.Title, 1, 20);allLetter(document.addCompign.Title); " name="Title" class="form-control" placeholder="Title" value="" required />
                        <span id="TitleError" class="text-danger"></span>
                      </div>
											<div class="form-group">
												<label for="Tags" class="laple-forms">Tags</label>
									      <input type="text" id="Tags" name="Tags" oninput=" stringlength(document.addCompign.Tags, 2, 20)"  class="form-control" placeholder="#Tags" value="" required />
                        <span id="TagsError" class="text-danger"></span>
                      </div>
                      <div class="form-group">
												<label for="Amount" class="laple-forms">Amount</label>
                        <input type="number" id="Amount" name="Amount" oninput="phonenumber(document.addCompign.Amount)"  class="form-control"  placeholder="0 $" value="" required/>
                        <span id="AmountError" class="text-danger"></span>
                      </div>
                      <div class="form-group">
												<label for="Deuration" class="laple-forms">End Date</label>
                        <input type="date" class="form-control" id="Deuration" name="Deuration"  placeholder="Add Deuration" value="" required/>
                        <span id="DeurationError" class="text-danger"></span>
                      </div>
                      
                      <div class="form-group">
                      <label for="gallery" class="laple-forms">Photo</label>
                      <input type="file" multiple class="form-control img-file-input" name="gallery"  id="gallery-photo-add">
                        <div class="container">
                          <div class="row">
                            <div class="gallery"></div>
                          </div>
                        </div>
                      </div>
                      <div class="form-group">
                      <label for="file" class="laple-forms">Feasibility study PDF</label>
                      <input type="file" class="form-control pdf-file-input" name="file">
                      </div>
                      <div class="form-group">
                      <textarea rows="4" cols="50" class="form-control" id="mytextarea" name="descrption">
                      </textarea>
                      <span id="descrptionError" class="text-danger"></span>

                      </div>

                      <center>
                      <input type="submit" class="btnadd"  value="Add" id="addComp" name="addComp"/>
							        <p class="p-login nots-p-reg" style="padding-top:20px">Visite my compaing!<a href="/auth/signup"> Click here</a></p>
                      </center>
										</div>
                  </form>
									</div>
								</div>

							</div>
						</div>
					</div>

				</div>
  </section>
	<!-- </div> -->
	<!-- profile page end -->
  <script>
$(document).ready(function(){
    $("#addComp").click(function(){  
		event.preventDefault();  
		if(Requirevalidation(document.addCompign.Title)&&Requirevalidation(document.addCompign.Tags)&&
		Requirevalidation(document.addCompign.Amount)&&Requirevalidation(document.addCompign.Deuration)&&
		$('#discription').val()!='')    
        serverSideValidate();
    });
});


function serverSideValidate(){
	
  $.ajax({
        url:"/validate",
        method:"POST",
             data:{
           type:"addCompain",
           formData:$('#addCompign').serialize()}
           ,
        success:function(data)
        {
      var result=JSON.parse(data);
    
      if(result.statusCode==200){
  
        $("#addCompign").submit(); // Submit the form
      }
      else{
          var error=JSON.parse(result.message);
          $.each( error, function( key, value ) {
            if(key=='msgState' || key=='main');
            else
            document.getElementById(key+'Error').innerHTML=value;
  
            });
            return false;}
        }
  
             });
        }
</script>
<?php  include  VIEW.'layouts'.DIRECTORY_SEPARATOR.'footer.phtml' ?>
