<?php

// include  VIEW.'layouts'.DIRECTORY_SEPARATOR.'head.phtml';
include  VIEW.'layouts'.DIRECTORY_SEPARATOR.'header.phtml'; ?>

<body>

  <!-- start pages photo -->
  <section class="cover-background top-space" style="background-image:url('/images/1(1).jpg');">
        <div class="opacity-medium bg-dark"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12 display-table page-title">
                    <div class="vertical-align-middle text-center">
                        <!-- start sub title -->
                        <span class="text-white text-shadow-black">Add Compigan</span>
                        <!-- end sub title -->
                        <!-- start page title -->
                        <h1 class="text-white text-shadow-black">you can add your compagin</h1>
                        <!-- end page title -->
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- end pages photo - -->


  <!-- profile page start-->
  <!-- <div class="main main-raised border-50 shadow-div col-md-12"> -->
	<section>
			<div class="container register">
					<div class="row">
						<div class="col-md-12 register-right shadow-div">
            <div class="tab-content" id="myTabContent">
								<div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
									<h3 class="register-heading">Add Your Compagin</h3>
									<div class="row register-form wow fadeIn">
                  <form class="col-md-12" action="/compaign/uploadFiles" id="addCompign" name="addCompign" method="post" enctype="multipart/form-data">
                  <!-- <form class="col-md-12" action="" name="addCompign" id="addCompign" method="post" enctype="multipart/form-data"> -->
										<div>
											<div class="form-group">
												<label for="Title" class="laple-forms">Title </label>
												<input type="text" id="Title" oninput="stringlength(document.addCompign.Title, 10, 50); " name="Title" class="form-control" placeholder="Title" value=""  />
                        <span id="TitleError" class="text-danger"></span>
                      </div>
											<div class="form-group">
												<label for="Tags" class="laple-forms">Tags</label>
									      <input type="text" id="Tags" name="Tags" oninput=" stringlength(document.addCompign.Tags, 2, 20)"  class="form-control" placeholder="#Tags" value=""  />
                        <span id="TagsError" class="text-danger"></span>
                      </div>
                      <div class="form-group">
												<label for="Amount" class="laple-forms">Amount</label>
                        <input type="number" id="Amount" name="Amount"   class="form-control"  placeholder="0 $" value="" />
                        <span id="AmountError" class="text-danger"></span>
                      </div>
                      <div class="form-group">
												<label for="Deuration" class="laple-forms">End Date</label>
                        <input type="date" class="form-control" id="Deuration" name="Deuration" oninput="validateDate(document.addCompign.Deuration)"  placeholder="Add Deuration" value="" />
                        <span id="DeurationError" class="text-danger"></span>
                      </div>
                      
                      <div class="form-group">
                      <label for="gallery" class="laple-forms">Photo</label>
                      <input type="file"  class="form-control img-file-input" name="gallery"  id="gallery-photo-add">
                        <div class="container">
                          <div class="row">
                            <div class="gallery"></div>
                          </div>
                        </div>
                      </div>
                      <div class="form-group">
                      <label for="file" class="laple-forms">Feasibility study PDF</label>
                      <input type="file" class="form-control pdf-file-input" name="file">
                      </div>
                      <div class="form-group">
                      <textarea rows="4" cols="50" class="form-control" id="mytextarea" value="" name="descrption">
                      </textarea>
                      <span id="descrptionError" class="text-danger"></span>

                      </div>

                      <center>
                      <input type="submit" class="btnadd"  value="Add" id="addComp" name="addComp" onclick="serverSideValidate();" />

                      <!-- <input type="submit" class="btnadd"  value="Add" id="addComp" name="addComp"/> -->
							        <p class="p-login nots-p-reg" style="padding-top:20px">Visite my compaing!<a href="#"> Click here</a></p>

                      </center>
                    
										</div>
                  </form>
                 
                  </div>
                  
								</div>

							</div>
						</div>
					</div>

				</div>
  </section>

<!-- Large modal -->
<button type="button" class="btn btn-primary"  id="loading" style="display: none;"   data-toggle="modal" data-target=".bd-example-modal-lg" data-keyboard="false" data-backdrop="static">loadding</button>

<div class="modal fade bd-example-modal-lg" tabindex="-1" style="top:20%;" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
  <div class="modal-content">
      <div class="modal-header" style="border: none !important;">
        </button>
      </div>
      <div class="modal-body">
        <div class="myprogress" id="progress_div">
          <svg class="progress-circle" width="200px" height="200px" xmlns="http://www.w3.org/2000/svg">
            <circle class="progress-circle-back"
                  cx="80" cy="80" r="74"></circle>
              <circle class="progress-circle-prog" 
                      cx="80" cy="80" r="74"></circle>
          </svg>
          <div class="progress-text" data-progress="0">0%</div>
      </div>
      <center>
    <span style="
    position: absolute;
    z-index: 1;
    top: 170px;
    color: #e4e4e4;
    font-size:24px;
    ">Loading...</span>
    </center>
    </div>
    <div class="modal-footer">
     
    </div>
    </div>
  </div>
</div>

<script src="/js/home/bootstrap.min.js"></script>

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7/jquery.js"></script> 
  <script type="text/javascript" src="/js/home/jquery.form.js"></script>
  <script type="text/javascript" >
     function upload_image() 
	{

		var bar = $('#bar');
		var percent = $('#percent1');
	
		$('#addCompign').ajaxForm({
			beforeSubmit: function() {
        document.getElementById("loading").click();
        progressBar(0,100);
			},
			uploadProgress: function(event, position, total, percentComplete) {
        progressBar(percentComplete,100);

			},
			success: function() {
        progressBar(100,100);

			},
			complete: function(xhr) {
				if(xhr.responseText)
				{
          window.location.replace("/home/index");
				}
			}
    }); 
  }
  
  
function progressBar(progressVal,totalPercentageVal = 100) {
		var strokeVal = (4.64 * 100) /  totalPercentageVal;
		var x = document.querySelector('.progress-circle-prog');
		x.style.strokeDasharray = progressVal * (strokeVal) + ' 999';
		var el = document.querySelector('.progress-text'); 
		var from = $('.progress-text').data('progress');
		$('.progress-text').data('progress', progressVal);
		var start = new Date().getTime();
	  
		setTimeout(function() {
			var now = (new Date().getTime()) - start;
			var progress = now / 700;
			el.innerHTML =Math.round(progressVal / totalPercentageVal * 100) + '%';
			if (progress < 1) setTimeout(arguments.callee, 10);
		}, 10);
	
	}
  
  function serverSideValidate(){	
    tinyMCE.triggerSave();
		if(Requirevalidation(document.addCompign.Title)&&Requirevalidation(document.addCompign.Tags)&&
		Requirevalidation(document.addCompign.Amount)&&Requirevalidation(document.addCompign.Deuration)&&
    Requirevalidation(document.addCompign.descrption)){
  $('#addCompign').ajaxForm({
        url:"/validate",
        type:"POST",
        data:{
           type:"addCompain",
           formData:$('#addCompign').serialize()}
        ,
        complete:function(xhr) {
				
      var result=JSON.parse(xhr.responseText);
    
      if(result.statusCode==200){
  
        // upload_image();
        alert('jjjjjjjj');
      }
      else{
        alert(result.message);
          var error=JSON.parse(result.message);
          i=1;
          $.each( error, function( key, value ) {
         
          
              if(key=='msgState' || key=='main'|| key=='userID'|| key=='userName'|| key=='type');
              else
              document.getElementById(key+'Error').innerHTML=value;
           
  
            });
            return false;}
        }
  
             }); 
            }
            else 
  event.preventDefault();  

  }   
            
  
</script>
    

