<?php

  include  VIEW.'layouts'.DIRECTORY_SEPARATOR.'header.phtml'; ?>



    <!-- start pages photo -->
    <section class="cover-background top-space" style="background-image:url('/images/home/1(1).jpg');">
        <div class="opacity-medium bg-dark"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12 display-table page-title">
                    <div class="vertical-align-middle text-center">
                        <!-- start sub title -->
                        <span class="text-white">Compagin</span>
                        <!-- end sub title -->
                        <!-- start page title -->
                        <h1 class="text-white">Welcome to My Compagin</h1>
                        <!-- end page title -->
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- end pages photo - -->
 <!-- latest compign -->
<section class="p-section">
<center>
  <h2 class="title-home">The Last Compagin</h2>
</center>

    <div class="container">
            <div class="row">
                <!-- details PHOTO -->
                <div class="col-md-8">
                                <form class="" action="" method="post" name='' id="">        
                                    <div class="col-md-6">
                                            <div class="form-group">
                                                <!-- <label for="country" class="laple-forms">Country</label> -->
                                                <select class="form-control form-control-allcomp" placeholder="your country" name="country">
                                                <option selected>All compagin</option>
                                                <option>Latest Compagin</option>
                                                <option>New Compagin</option>
                                                </select>  
                                            </div>
                                    </div>
                                </form> 
                </div>                   
            </div>                   
    </div>                   
<div class="container">
<!-- <div class="row"> -->
<div class="tab-pane text-center gallery" id="works">
          <div class="row">
              <div class="col-md-4 img-overlay">
                  <div class="card">
                      <img class="card-img-top" src="/images/home/1(5).jpg" alt="Card image cap">
                      <div class="overlay">
                      <div class="text-overlay"> 
                        <h5 class="card-title">compagin</h5>
                        <p class="card-text">Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
                        <a href="#" class="btn btn-home-comp">Go somewhere</a>
                      </div>
                      </div>
                  </div>
              </div>
              <div class="col-md-4 img-overlay">
                  <div class="card">
                      <img class="card-img-top" src="/images/home/1(3).jpg" alt="Card image cap">
                      <div class="overlay">
                      <div class="text-overlay"> 
                      <h5 class="card-title">compagin</h5>
                        <p class="card-text">Lorem ipsum dolor sit amet consectetur adipisicing elit</p>
                        <a href="#" class="btn btn-home-comp">Go somewhere</a>
                      </div>
                      </div>
                  </div>
              </div>
              <div class="col-md-4 img-overlay">
                  <div class="card">
                      <img class="card-img-top" src="/images/home/1(6).jpg" alt="Card image cap">
                      <div class="overlay">
                      <div class="text-overlay"> 
                        <h5 class="card-title">compagin</h5>
                        <p class="card-text">Lorem ipsum dolor sit amet consectetur adipisicing elit</p>
                        <a href="#" class="btn btn-home-comp">Go somewhere</a>
                      </div>
                      </div>
                  </div>
              </div>

              <div class="col-md-4 img-overlay">
                  <div class="card">
                      <img class="card-img-top" src="/images/home/1(5).jpg" alt="Card image cap">
                      <div class="overlay">
                      <div class="text-overlay"> 
                        <h5 class="card-title">compagin</h5>
                        <p class="card-text">Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
                        <a href="#" class="btn btn-home-comp">Go somewhere</a>
                      </div>
                      </div>
                  </div>
              </div>
              <div class="col-md-4 img-overlay">
                  <div class="card">
                      <img class="card-img-top" src="/images/home/1(3).jpg" alt="Card image cap">
                      <div class="overlay">
                      <div class="text-overlay"> 
                      <h5 class="card-title">compagin</h5>
                        <p class="card-text">Lorem ipsum dolor sit amet consectetur adipisicing elit</p>
                        <a href="#" class="btn btn-home-comp">Go somewhere</a>
                      </div>
                      </div>
                  </div>
              </div>
              <div class="col-md-4 img-overlay">
                  <div class="card">
                      <img class="card-img-top" src="/images/home/1(6).jpg" alt="Card image cap">
                      <div class="overlay">
                      <div class="text-overlay"> 
                        <h5 class="card-title">compagin</h5>
                        <p class="card-text">Lorem ipsum dolor sit amet consectetur adipisicing elit</p>
                        <a href="#" class="btn btn-home-comp">Go somewhere</a>
                      </div>
                      </div>
                  </div>
              </div>
          </div>
          
          <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center">
                <li class="page-item">
                <a class="page-link" href="#" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                    <span class="sr-only">Previous</span>
                </a>
                </li>
                <li class="page-item"><a class="page-link" href="#">1</a></li>
                <li class="page-item"><a class="page-link" href="#">2</a></li>
                <li class="page-item"><a class="page-link" href="#">3</a></li>
                <li class="page-item">
                <a class="page-link" href="#" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                    <span class="sr-only">Next</span>
                </a>
                </li>
            </ul>
          </nav>
        
         
  </div>
</div>

</div>
</section>
<!-- latest Compaign -->


<script src="/js/home/jquery-3.4.1.slim.min.js"></script>
<script src="/js/home/js.js"></script>
<script src="/js/home/popper.min.js"></script>
<script src="/js/home/bootstrap.min.js"></script>
<script src="/js/home/wow.min.js"></script>
<script src="/js/home/main.js"></script>

<script>
new WOW().init();
</script>
<?php  include  VIEW.'layouts'.DIRECTORY_SEPARATOR.'footer.phtml' ?>
