<?php

  include  VIEW.'layouts'.DIRECTORY_SEPARATOR.'header.phtml'; ?>



    <!-- start pages photo -->
    <section class="cover-background top-space" style="background-image:url('/images/home/1(1).jpg');">
        <div class="opacity-medium bg-dark"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12 display-table page-title">
                    <div class="vertical-align-middle text-center">
                        <!-- start sub title -->
                        <span class="text-white"><?php echo $lang['item40']?></span>
                        <!-- end sub title -->
                        <!-- start page title -->
                        <h1 class="text-white"><?php echo $lang['item41']?></h1>
                        <!-- end page title -->
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- end pages photo - -->


<section>
	<div class="container register">
		<div class="row">
			<div class="col-md-12 register-left">
				<h3 class="text-blue"><?php echo $lang['item42']?></h3>

			</div>
				<div class="col-md-12">
					<div class="tab-content" id="myTabContent">
							<div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
						     <form class="" action="" method="post" name='signupForm' id="signupForm">
								<div class="row contact-form ">
								<div class="col-md-6">
										<div class="form-group">
											<label for="name" class="laple-forms"><?php echo $lang['item43']?></label>
											<input type="text" class="form-control" placeholder="<?php echo $lang['item43']?> *"  name="name" value='<?php if(isset($_POST['first_name']))echo$_POST['first_name'];?>' oninput=" stringlength(document.signupForm.first_name,5,12); allLetter(document.signupForm.first_name);preventSpace(document.signupForm.first_name,0,0)" />
										<?php echo Message::check('first_name');  ?>
										<span class="text-danger text-error" id="first_nameError"> </span>
										</div>
                                </div>		
                                <div class="col-md-6">
                                <div class="form-group">
										<label for="email" class="laple-forms"><?php echo $lang['item44']?></label>
											<input type="email" name="email" class="form-control" placeholder="<?php echo $lang['item44']?> *" value='<?php if(isset($_POST['email']))echo$_POST['email'];?>' oninput=" ValidateEmail(document.signupForm.email);" />
											<?php echo Message::check('email');  ?>
											<span class="text-danger text-error" id="emailError"> </span>
										</div>
                                </div>
										<div class="col-md-12">
										<div class="form-group">
										<label for="message" class="laple-forms"><?php echo $lang['item45']?></label>
										<textarea rows="4" cols="50" type="text" class="form-control" placeholder="<?php echo $lang['item45']?> *"  name="message"></textarea>
										</div>
										</div>
                                        </div>
                                        <center>
										<input id="signuptBtn" type="submit" class="btncontactus float-none" value="<?php echo $lang['item46']?>"/>
										</center>
										</div>
					         </form>
				            </div>
				</div>
		</div>
	</div>
</section>
	

<?php  include  VIEW.'layouts'.DIRECTORY_SEPARATOR.'footer.phtml' ?>
