<?php

  include  VIEW.'layouts'.DIRECTORY_SEPARATOR.'header.phtml';
  $compaign=$this->view_data['compaign'][0]; ?>
    <!-- <link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css"> -->
<script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!-- Modal -->
<div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle"><i class="fas fa-donate"></i>DONATIONS (<span class="donars"></span>)</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div>
          <?php
            if (array_key_exists('donars',$this->view_data)){
            $html='';
            foreach ($this->view_data['donars'] as $donar) {
              $html.='<div class="donar-user">';
              $html.='<div class="d-inline">';
              $html.='  <img src="/images/home/user.jpg" alt="Profile img" height="30" width="30" class="pic-profile-header" title="">';
              $html.='</div> <div class="d-inline-block"> <h5>';
              $html.=Helper::userName($donar['user_id']);
              $html.='/<span class="amount">';
              $html.=$donar['amount'];
              $html.='</span></h5></div>
              <hr class="hr-blue-80">
          </div>
          </div>';

            }
          echo $html;
          }
            ?>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btnmodel float-none" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<!-- modal -->


<!-- start pages photo -->
<section class="cover-background top-space" style="background-image:url('/images/home/1(1).jpg');">
    <div class="opacity-medium bg-dark"></div>
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12 display-table page-title">
                <div class="vertical-align-middle text-center">
                    <!-- start sub title -->
                    <span class="text-white"><?php echo $lang['item70']; ?></span>
                    <!-- end sub title -->
                    <!-- start page title -->
                    <h1 class="text-white"><?php echo $lang['item71']; ?></h1>
                    <!-- end page title -->
                </div>
            </div>
        </div>
    </div>
</section>
<!-- end pages photo - -->

<div class="main main-raised border-50">
    <div class="details-content">
        <div class="container">
            <div class="row">
                <!-- details PHOTO -->
                <div class="col-md-8 col-xs-12">
                    <div class="details">
                        <div class="text-center mt-50px">
                        <h4 class="text-left"><?php echo $compaign['title']; ?></h4>
                            <div class="">
                            <img src='/uploads/<?php echo $compaign["galary"]; ?>' class="img-raised img-fluid" width="auto">
                            </div>
                        <h5 class="text-left by-user">
                          <a href="/profile/showProfile/<?php echo $compaign['owner_id']; ?>">  <i class="fas fa-pen-alt"></i> <?php echo $lang['item72']; ?>: <span><?php echo Helper::userName( $compaign['owner_id']); ?></span></h5></a>                       
                    <div class="compagin-content">
                            <p class="text-left">
                              <?php echo $compaign['descrption']; ?>
                            </p>
                        </div>

                        <!-- comments -->
                                <div class="col-sm-10 col-sm-offset-1" id="login">
                                  
                                        <div>
                                            <div class="tab-pane active" id="comments-login">
                                                <ul class="media-list" id="comments-show">
                                                  
                                                </ul>
                                            </div>
                                            <div>
                                                <!-- <p class="p-login nots-p-reg">You have already account! <a href="/auth/login">LogIn</a></p> -->
                                                    <div class="form-group">
                                                        <label for="email" class="col-sm-2 control-label"><?php echo $lang['item73']; ?></label>
                                                        <div class="col-sm-10">
                                                        <textarea class="form-control" name="Comment" id="Comment" rows="5" oninput="if($('#Comment').val()!='')$('#submitComment').attr('disabled' , false ); else $('#submitComment').attr('disabled' , 'disabled' );"></textarea>
                                                        </div>
                                                    </div>
                                                    <div class="form-group">
                                                        <div class="col-sm-offset-2 col-sm-10">
                                                            <button class="btn btn-success btn-circle text-uppercase" disabled='disabled' onclick="add_comment()" type="submit" id="<?php echo $lang['item74']; ?>"><span class="glyphicon glyphicon-send"></span> Summit comment</button>
                                                        </div>
                                                    </div>
                                            </div>
                                        </div>
                                    
                                </div>

                        <!-- comments -->
                    </div>
                    </div>
                </div>
                <!-- details PHOTO -->
                <!-- details PHOTO -->
                <div class="col-md-4 col-xs-12">
                    <div class="details">

                        <div class="mt-50px">
                        <div class="container">
                        <h3 class="text-center text-blue"><span class="collection">0.0</span> <span>$ </span><span class="goal-num"><?php echo $lang['item75']; ?> $<span class="cost"><?php echo $compaign['cost']; ?></span> <?php echo $lang['item76']; ?></span></h3>
                            <div class="progress progress-details">
                            <div class="progress-bar bg-yellow" role="progressbar" style="width: 2%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
                            </div>
                         <a href="" class="a-donars" data-toggle="modal" data-target="#exampleModalLong"><h5 class="text-center text-black"><i class="fas fa-donate"></i><?php echo $lang['item77']; ?> <span class="donars-num donars">00</span></h5></a>
                            <center>
                            <a href="/donate/index/<?php echo $compaign['id'] ?>"><input type="submit" id="donate" class="btndonate float-none"  value="<?php echo $lang['item78']; ?>"/></a>
                            </center>
                        </div>

                            <div class="">
                            <!-- <img src="/images/home/1(2).jpg" class="img-raised img-fluid" width="auto"> -->
                            </div>
                        </div>
                    </div>
                </div>
                <!-- details PHOTO -->

            </div>
        </div>
  	</div>
</div>


<script type="text/javascript">
new WOW().init();
function getAmount() {
  var amount = $(".amount");

  var collect=0;

  for(var i = 0; i < amount.length; i++){

      collect+=parseInt($(amount[i]).text());
  }
  $(".donars").text(i);
  return collect;
}
function percentage() {
  var cost=parseInt($(".cost").text());
var prec=(getAmount()/cost)*100;
return prec;

}

$( document ).ready(function() {
    $(".collection").text(getAmount());
    $(".progress-bar").css("width",percentage()+"%");

});


      function load_comment(){
        jQuery_1_3_2.ajax({
            url:"/detailsCompagin",
            method:"POST",
            data:{type:"getcomment",
            id:<?php echo $compaign['id'] ?>
            },
            success:function(data)
            {
              html='';
              var comments=JSON.parse(data);
              // alert(d)

              $.each( comments.data, function( index, row ) {
          html+='<li class="media">'+
                '<a class="pull-left" href="#">'+
                  '<img class="media-object rounded-circle" src="https://s3.amazonaws.com/uifaces/faces/twitter/dancounsell/128.jpg" alt="profile">'+
                  '</a>'+
                  '<div class="media-body">'+
                  '<div class="well well-lg">'+
                  '<h5 class="media-heading text-uppercase reviews">'+row.name+
                  '</h5><ul class="media-date text-uppercase reviews list-inline">'+
                  '<span class="date-comm">'+row.created_at+
                  '</span></ul><p class="media-comment">'+row.message+
                  '</p></div></div></li>'+
                  '<hr class="hr-blue-80">';
            });
            $('#comments-show').html(html);

          }
      });
      }
      $(document).ready(function(){
              load_comment();
        });


        function add_comment(){
          comm =$('#Comment').val();

        jQuery_1_3_2.ajax({
            url:"/detailsCompagin",
            method:"POST",
            data:{type:"addcomment",
            id:<?php echo $compaign['id'];?>,
            comment: comm
            },
            success:function(data)
            {
              var comments=JSON.parse(data);
              if(comments.statusCode=='200'){
                $('#Comment').val('');
                load_comment()  

              }

          }
      });
          
      }
</script>


<?php  include  VIEW.'layouts'.DIRECTORY_SEPARATOR.'footer.phtml' ?>
