<?php

  include  VIEW.'layouts'.DIRECTORY_SEPARATOR.'header.phtml';
  $compaign=$this->view_data['compaign'][0]; ?>
  
<!-- start pages photo -->
<section class="cover-background top-space section-img" >
    <div class="opacity-medium bg-dark"></div>
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12 display-table page-title">
                <div class="vertical-align-middle text-center">
                    <!-- start sub title -->
                    <span class="text-white"><?php echo $lang['item70']; ?></span>
                    <!-- end sub title -->
                    <!-- start page title -->
                    <h1 class="text-white"><?php echo $lang['item71']; ?></h1>
                    <!-- end page title -->
                </div>
            </div>
        </div>
    </div>
</section>
<!-- end pages photo - -->

<section>
<div class="container-flauid m-5 ">
<div class="row">
  <div class="col-lg-8 pt-3 pr-5 bg-white"  >
  <h1 class='titleD'><?php echo $compaign['title']; ?></h1>
    <span class="dateD">
    By Hopes news - <?php echo $compaign['created_at']; ?>     
      </span>
      <img src='/uploads/<?php echo $compaign["galary"]; ?>'  class="img-fluid mt-4 imgD" alt="">
      <p  class="mt-4 discD" >
   <?php echo $compaign['descrption']; ?>
    </p>

    <div class="mt-4">
								<span class="mr-3 tag-title">
									Tags:
								</span>
								
								<span >
									<a href="#" class="ml-3">
										#Streetstyle
									</a>

									<a href="#" class="ml-3">
										#Crafts
                  </a>
                  <a href="#" class="ml-3">
										#Streetstyle
									</a>

									<a href="#" class="ml-3">
										#Crafts
									</a>
								</span>
							
     </div>
     <br>
     <hr>

     <h2 class="mt-4 comm-title">Last Comments</h2> <br>
    <div class="comments  mt-0 mr-5 ml-5" id="comments-show"></div>
  <hr>
        <div  class="comm" class="p-5" >
          <h2   class='comm-sub'>Leave a comment</h2> <br>
        <form action="#" id="comm_form" >
          <input type="hidden" name="type" value="2">
                      <div class="wrap-input100 comm-length" >
                        <textarea class="input100"     name="Comment" id="Comment" oninput="if($('#Comment').val()!='')$('#submitComment').attr('disabled' , false ); else $('#submitComment').attr('disabled' , 'disabled' );">
                        </textarea>
                        <span class="focus-input100" data-placeholder="comment"></span>
                      </div>
                       
        </form>
                          <div class="form-group">
                          <button class="btn btn-dark text-uppercase"  disabled='disabled'  onclick="add_comment()" type="submit" id="submitComment"><span class="glyphicon glyphicon-send"></span> <?php echo $lang['item74']; ?></button>

                          </div>
        </div>

    </div>
  <div class="col-lg-4 mt-3 side-bar">
   
   <div class="list-group side-title" >
   <h2 class=" card-title group-title "> Compaign Details</h2>  
   <div>
        <div class='countD donate-count'><i class='fas fa-donate'></i>        <i>300K</i> </div>
        <div class='countD follow-count'><i class='fas fa-eye'></i>        <i>300K</i> </div>
        <div class='countD comm-count' ><i class='fas  fa-comment-dots'></i>        <i>300K</i> </div>

</div>
<br>
        <div class="container">
          <div class="progress progress-details">
            <div class="progress-bar bg-yellow" role="progressbar" style="width: 2%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
          </div>
          <h3 class="text-center text-blue"> <span class="goal-num">0.0$ <?php echo $lang['item75']; ?> $<span class="cost"><?php echo $compaign['cost']; ?></span> <?php echo $lang['item76']; ?></span></h3>
        </div>
        
                            <center>
                            <a href="/donate/index/<?php echo $compaign['id'] ?>"><input type="submit" id="donate" class="btndonate float-none"  value="<?php echo $lang['item78']; ?>"/></a>
                            <?php
                             if(!in_array(Session::get('userID'),$this->view_data['followers'])){ ?>
                              <input type="button" id="follow" onclick="follow('follow')" class="btndonate float-none"  value="متابعة"/>
                            <?php } else{ ?>
                              <input type="button" id="follow" onclick="follow('unfollow')" class="btndonate float-none"  value="الغاء المتابعة"/>
                              <?php } ?>
                            </center>
       
   </div>

   <div class="list-group donors-title "  >
   <h2 class=" card-title group-title "> <?php echo $lang['item77']; ?></h2>  

   <?php 
                         $donars=$this->view_data['donars'];
                         foreach($donars as $donar){
                       ?>
                       <a class="pull-left" href="#">
                  <span class="donars-amount" > <?php echo $donar['amount'].'$' ?></span></span>
                  </a>
                  <span  class='donars-name'>
                  <?php echo Helper::userName($donar['user_id']) ?></span><br>
                  
         <?php
         }
?>
                     <center>
                    <button  data-toggle="modal" data-target="#donarsModal" id="donate" class="btndonate float-none"  >View all donars</abutton>
                    </center>     
   </div>

   <div class="list-group follow-title"  >
   <h2 class=" card-title group-title "> FOLLOWERs</h2>  
   <?php 
                         $followers=$this->view_data['followers'];
                         foreach($followers as $follower){
                       ?>
                       <a class="pull-left" href="#">
                  <img class="media-object rounded-circle follow-img" src="/images/home/user.jpg"  alt="profile">
                  </a>
                  <span  class='follow-name'>
                  <?php echo Helper::userName($follower) ?></span><br>
                  
         <?php
         }
         ?>
                <center>
                    <button  data-toggle="modal" data-target="#followerModal" id="donate" class="btndonate float-none"  >View all followers</abutton>
                </center>   
   </div>
</div>
</div>
</div>
</section>




<!-- Modal -->
<div class="modal fade" id="donarsModal" tabindex="-1" role="dialog" aria-labelledby="donarsModalTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="donarsModalTitle"> ALL Donars </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
         
      <?php
            if (array_key_exists('donars',$this->view_data)){
            foreach ($this->view_data['donars'] as $donar) {
              ?>
              <div class="donar-user">
              <div class="d-inline">
                <img src="/images/home/user.jpg" alt="Profile img" height="30" width="30" class="pic-profile-header" title="">
              </div> <div class="d-inline-block"> <h5>
               <?php echo Helper::userName($donar['user_id']); ?>
                <span class="amount">
                <?php echo $donar['amount']; ?>
              </span></h5></div>
              <hr class="hr-blue-80">
          </div>
            <?php }
            }
            ?>
        </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>


<!-- /////////////////// -->


<!-- Modal -->
<div class="modal fade" id="followerModal" tabindex="-1" role="dialog" aria-labelledby="followerModalTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="followerModalTitle"> ALL Followes </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
         
      <?php
            if (array_key_exists('followers',$this->view_data)){
            foreach ($this->view_data['followers'] as $follower) {
              ?>
              <div class="donar-user">
              <div class="d-inline">
                <img src="/images/home/user.jpg" alt="Profile img" height="30" width="30" class="pic-profile-header follow-img" title="">
              </div> <div class="d-inline-block"> <h5>
               <?php echo Helper::userName($follower); ?>
                </h5></div>
              <hr class="hr-blue-80">
          </div>
            <?php }
            }
            ?>
        </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>



<script type="text/javascript">
function getAmount() {
  var amount = $(".amount");

  var collect=0;

  for(var i = 0; i < amount.length; i++){

      collect+=parseInt($(amount[i]).text());
  }
  $(".donars").text(i);
  return collect;
}
function percentage() {
  var cost=parseInt($(".cost").text());
var prec=(getAmount()/cost)*100;
return prec;

}

$( document ).ready(function() {
    $(".collection").text(getAmount());
    $(".progress-bar").css("width",percentage()+"%");
    load_comment();

});


      function load_comment(){
        jQuery_1_3_2.ajax({
            url:"/detailsCompagin",
            method:"POST",
            data:{type:"getcomment",
            id:<?php echo $compaign['id'] ?>
            },
            success:function(data)
            {
              html='';
              var comments=JSON.parse(data);
              // alert(d)
   
              $.each( comments.data, function( index, row ) {
          html+='<div  class="comm"  >'+
                '<a class="pull-left" href="#">'+
                  '<img class="media-object rounded-circle comm-img" src="/images/home/user.jpg"  alt="profile">'+
                  '</a>'+
                  '<span class="comm-name">'+
                  row.name+'</span><br>'+
                  '<p class="comm-date">'+' '+row.created_at+'</p>'+
                  '<span class="comm-txt">'+row.message+
                  '</span></div>';
            });
            $('#comments-show').html(html);

          }
      });
      }
    
        function add_comment(){
          comm =$('#Comment').val();

        jQuery_1_3_2.ajax({
            url:"/detailsCompagin",
            method:"POST",
            data:{type:"addcomment",
            id:<?php echo $compaign['id'];?>,
            comment: comm
            },
            success:function(data)
            {
              var comments=JSON.parse(data);
              if(comments.statusCode=='200'){
                $('#Comment').val('');
                load_comment()  

              }

          }
      });
          
      }

      function follow(method){
        jQuery_1_3_2.ajax({
            url:"/follow",
            method:"POST",
            data:{method:method,
            cid:<?php echo $compaign['id'] ?>,
            owner:<?php echo $compaign['owner_id'] ?>
            },
            success:function(data)
            {
              var result=JSON.parse(data);
                if(result.statusCode==200)
                   location.reload();
            }
          });
        }

</script>


<?php  include  VIEW.'layouts'.DIRECTORY_SEPARATOR.'footer_section.phtml' ?>
<?php  include  VIEW.'layouts'.DIRECTORY_SEPARATOR.'footer.phtml' ?>
