<?php

  include  VIEW.'layouts'.DIRECTORY_SEPARATOR.'header.phtml';
  $compaign=$this->view_data['compaign'];

  $donars=$this->view_data['donars']; ?>
      <!-- <link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css"> -->
<!-- Modal -->
<div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">DONATIONS (4.3K)</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div>


          <?php
            if (array_key_exists('donars',$this->view_data)){
            $html='';
            foreach ($this->view_data['donars'] as $donar) {
              $html.='<div class="donar-user">';
              $html.='<div class="d-inline">';
              $html.='  <img src="/images/home/user.jpg" alt="Profile img" height="30" width="30" class="pic-profile-header" title="">';
              $html.='</div> <div class="d-inline-block"> <h5>';
              $html.=Helper::userName($donar['user_id']);
              $html.='/<span class="amount">';
              $html.=$donar['amount'];
              $html.='</span></h5></div>
              <hr class="hr-blue-80">
          </div>
          </div>';

            }
          echo $html;
          }
            ?>

        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btnmodel float-none" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<!-- modal -->

<!-- start pages photo -->
<section class="cover-background top-space" style="background-image:url('/images/home/1(1).jpg');">
    <div class="opacity-medium bg-dark"></div>
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12 display-table page-title">
                <div class="vertical-align-middle text-center">
                    <!-- start sub title -->
                    <span class="text-white">Compagin</span>
                    <!-- end sub title -->
                    <!-- start page title -->
                    <h1 class="text-white">Compagin Details</h1>
                    <!-- end page title -->
                </div>
            </div>
        </div>
    </div>
</section>
<!-- end pages photo - -->

<div class="main main-raised border-50">
    <div class="details-content">
        <div class="container">
            <div class="row">
                <!-- details PHOTO -->
                <div class="col-md-8 col-xs-12">
                    <div class="details">
                    <div class="col-md-12">
                        <div class="tab-content" id="myTabContent">
                                <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                                    <h2 class="text-center text-blue">Donate Now</h2>
                                <form class="" action="/donate/submitform" method="post" name='DonateForm' id="DonateForm">
                                  <input type="hidden" name="compaign_id" value="<?php echo $compaign['id']; ?>">
                                    <div class="row register-form ">
                                    <div class="col-md-12">
                                            <div class="form-group">
                                                <label for="Donation" class="laple-forms">your Donation</label>
                                                <input type="number" class="form-control donate-dollar" placeholder="0.0 $"  name="Donation"/>
                                                <?php echo Message::check('Donation');  ?>
                          											<span class="text-danger text-error" id="DonationError"> </span>

                                            </div>
                                    </div>
                                    <div class="col-md-6">
                                            <div class="form-group">
                                                <label for="country" class="laple-forms">Country</label>
                                                <select class="form-control" class="form-control" placeholder="your country" name="country">
                                                <option selected>Select Your Country</option>
                                                <option>Yemen</option>
                                                <option>Yemen</option>
                                                <option>Yemen</option>
                                                <option>Yemen</option>
                                                </select>
                                                <?php echo Message::check('country');  ?>
                                                <span class="text-danger text-error" id="countryError"> </span>
                                            </div>
                                    </div>
                                    <div class="col-md-6">
                                    <div class="form-group">
                                            <label for="code" class="laple-forms">Zip Code</label>
                                            <input type="text" name="code" class="form-control" placeholder="Your Code " value='' oninput="" />
                                            <?php echo Message::check('code');  ?>
                                            <span class="text-danger text-error" id="codeError"> </span>
                                        </div>
                                    </div>

                                    <div class="col-md-12">
                                            <div class="form-group">
                                                <label for="nebit-number" class="laple-forms">Credit or Debit Number</label>
                                                <input type="text" class="form-control" placeholder="Debit Number" name="debitNumber"/>
                                                <?php echo Message::check('debitNumber');  ?>
                                                <span class="text-danger text-error" id="debitNumberError"> </span>
                                            </div>
                                    </div>

                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="month" class="laple-forms">Expiration Month</label>
                                            <select class="form-control" class="form-control" name="month">
                                                <option class="selected">Select Expiration Month</option>
                                                <option>02-Jun</option>
                                                <option>02-Feb</option>
                                                <option>02-Oct</option>
                                                <option>02-Nov</option>
                                                </select>
                                                <?php echo Message::check('month');  ?>
                                                <span class="text-danger text-error" id="monthError"> </span>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="year" class="laple-forms">Expiration Year</label>
                                            <select class="form-control" class="form-control" name="year">
                                                <option class="selected">Select Expiration Year</option>
                                                <option>2020</option>
                                                <option>2021</option>
                                                <option>2023</option>
                                                <option>2024</option>
                                                </select>
                                                <?php echo Message::check('year');  ?>
                                                <span class="text-danger text-error" id="yearError"> </span>
                                        </div>
                                    </div>

                                                </div>
                                                <center>
                                                    <input type="submit"  style="display: none;" id='ajaxSubmit'  value="Add"  name="addDonation" onclick="upload_to_db();" />
                                            <!-- <input id="DonateBtn" type="submit" class="btnRegister float-none"  value="Donate Now"/> -->
                                            <button type="button" class="btnadd"  value="Add" id="DonateBtn" name="addComp"  />Donate Now</button>

                                            </center>
                                            </div>
                                </form>
                                </div>
                        </div>
                    </div>
                </div>
                <!-- details PHOTO -->
                <!-- details PHOTO -->
                <div class="col-md-4 col-xs-12 box-donate">
                    <div class="details">

                        <div class="mt-50px">
                        <div class="container">
                        <h4 class="text-center"><?php echo $compaign['title']; ?></h4>

                      <h3 class="text-center text-blue"><span class="collection">0.0</span> <span>$ </span><span class="goal-num">raised of $<span class="cost"><?php echo $compaign['cost']; ?></span> goal</span></h3>
                            <div class="progress progress-details">
                            <div class="progress-bar bg-yellow" role="progressbar" style="width: 25%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
                            </div>
                            <div class="">
                            <img src="/uploads/<?php echo $compaign['galary']; ?>" class="pt-10px img-fluid" width="auto">
                            </div>
                            <div class="text-center p-all-10">
                                <p><?php echo $compaign['descrption']; ?></p>
                            </div>
                         <a href="" class="a-donars" data-toggle="modal" data-target="#exampleModalLong"><h5 class="text-center text-black"><i class="fas fa-donate"></i>Donars <span class="donars-num">300K</span></h5></a>

                        </div>
                        </div>
                    </div>
                </div>
                <!-- details PHOTO -->

            </div>
        </div>
  	</div>
</div>
<!-- Large modal -->
<button type="button" class="btn btn-primary"  id="loading" style="display: none;"   data-toggle="modal" data-target=".bd-example-modal-lg" data-keyboard="false" data-backdrop="static">loadding</button>

<div class="modal fade bd-example-modal-lg" tabindex="-1" style="top:20%;" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
  <div class="modal-content">
      <div class="modal-header" style="border: none !important;">
        </button>
      </div>
      <div class="modal-body">
        <div class="myprogress" id="progress_div">
          <svg class="progress-circle" width="200px" height="200px" xmlns="http://www.w3.org/2000/svg">
            <circle class="progress-circle-back"
                  cx="80" cy="80" r="74"></circle>
              <circle class="progress-circle-prog"
                      cx="80" cy="80" r="74"></circle>
          </svg>
          <div class="progress-text" data-progress="0">0%</div>
      </div>
      <center>
    <span style="
    position: absolute;
    z-index: 1;
    top: 170px;
    color: #e4e4e4;
    font-size:24px;
    ">Loading...</span>
    </center>
    </div>
    <div class="modal-footer">

    </div>
    </div>
  </div>
</div>

<script src="/js/home/bootstrap.min.js"></script>

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7/jquery.js"></script>
  <script type="text/javascript" src="/js/home/jquery.form.js"></script>

<script type="text/javascript">
var jQuery_form = $.noConflict(true);
</script>

<script type="text/javascript">
function getAmount() {
  var amount = $(".amount");

  var collect=0;

  for(var i = 0; i < amount.length; i++){

      collect+=parseInt($(amount[i]).text());
  }
  $(".donars").text(i);
  return collect;
}
function percentage() {
  var cost=parseInt($(".cost").text());
var prec=(getAmount()/cost)*100;
return prec;

}

$( document ).ready(function() {
    $(".collection").text(getAmount());
    $(".progress-bar").css("width",percentage()+"%");

});

$(document).ready(function(){
    $("#DonateBtn").click(function(){
       event.preventDefault();
		if(Requirevalidation(document.DonateForm.Donation)&&Requirevalidation(document.DonateForm.country)&&
		Requirevalidation(document.DonateForm.code)&&Requirevalidation(document.DonateForm.debitNumber)&&
		Requirevalidation(document.DonateForm.month)&&Requirevalidation(document.DonateForm.year)){
			serverSideValidate()


		}
    });
});


function serverSideValidate(){

jQuery_1_3_2.ajax({
			url:"/validate",
			method:"POST",
     	    data:{
				 type:"addDonation",
				 formData:$('#DonateForm').serialize()}
				 ,
			success:function(data)
			{
		var result=JSON.parse(data);

		if(result.statusCode==200){

		document.getElementById("ajaxSubmit").click();// Submit the form
		}
		else{
				var error=JSON.parse(result.message);
				$.each( error, function( key, value ) {
					if(key=='msgState' || key=='main');
					else
					document.getElementById(key+'Error').innerHTML=value;

					});
					return false;

			}
      }


			   });
			}

      function upload_to_db()
   {
     tinyMCE.triggerSave();

       jQuery_form('#DonateForm').ajaxForm({
       beforeSubmit: function() {

         document.getElementById("loading").click();
         progressBar(0,100);
       },
       uploadProgress: function(event, position, total, percentComplete) {

         progressBar(percentComplete,100);

       },
       success: function() {
         progressBar(100,100);

       },
       complete: function(xhr) {
         if(xhr.responseText)
         {
           progressBar(100,100);
           setTimeout(function () {
              window.location.replace("/home/index");
           },1000)

         }
       }
     });
   // }
   // else
   // event.preventDefault();

 }
 function progressBar(progressVal,totalPercentageVal = 100) {
 		var strokeVal = (4.64 * 100) /  totalPercentageVal;
 		var x = document.querySelector('.progress-circle-prog');
 		x.style.strokeDasharray = progressVal * (strokeVal) + ' 999';
 		var el = document.querySelector('.progress-text');
 		var from = $('.progress-text').data('progress');
 		$('.progress-text').data('progress', progressVal);
 		var start = new Date().getTime();

 		setTimeout(function() {
 			var now = (new Date().getTime()) - start;
 			var progress = now / 700;
 			el.innerHTML =Math.round(progressVal / totalPercentageVal * 100) + '%';
 			if (progress < 1) setTimeout(arguments.callee, 10);
 		}, 10);

 	}
</script>


<?php  include  VIEW.'layouts'.DIRECTORY_SEPARATOR.'footer.phtml' ?>
