<?php

if(!Session::logged())
  header('location:/home/index');
  include  VIEW.'layouts'.DIRECTORY_SEPARATOR.'header.phtml'; ?>
    <!-- start pages photo -->
    <section class="cover-background top-space" style="background-image:url('/images/home/1(1).jpg');">
        <div class="opacity-medium bg-dark"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12 display-table page-title">
                    <div class="vertical-align-middle text-center">
                        <!-- start sub title -->
                        <!-- <span class="text-white">Profile</span> -->
                        <!-- end sub title -->
                        <!-- start page title -->
                        <h1 class="text-white"><?php echo $lang['item130']?> </h1>
                        <!-- end page title -->
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- end pages photo - -->

    <!-- profile page start-->

    <section>
   <div class="container-login100">
			<div class="wrap-login100 signup700 " style="width: 1000px" >
				<form class="login100-form validate-form"  action="" method="post"  name="editFormProfile" id="editFormProfile">
				
					<div class="wrap-input100 validate-input" >
                        <label for="first_name" class="laple-forms"><?php echo $lang['item22']?> </label>
						<input class="input100" type="text" name="first_name"  value='<?php if(isset($_POST['first_name']))echo$_POST['first_name']; else echo $this->view_data['editeProfile'][0]['value'];?>' oninput=" stringlength(document.signupForm.first_name,5,12); allLetter(document.signupForm.first_name);preventSpace(document.signupForm.first_name,0,0)" />
						<span class="text-danger text-error" id="first_nameError"> </span>
					</div>

					<div class="wrap-input100 validate-input" >
                       <label for="last_name" class="laple-forms"><?php echo $lang['item23']?> </label>
						<input class="input100" type="text" name="last_name"  value='<?php if(isset($_POST['last_name']))echo$_POST['last_name']; else echo $this->view_data['editeProfile'][1]['value'];?>'  oninput=" stringlength(document.signupForm.last_name,5,12); allLetter(document.signupForm.last_name);preventSpace(document.signupForm.first_name,0,0)">
						<span class="text-danger text-error" id="last_nameError"> </span>
                    </div>
                    
                    <div class="wrap-input100 validate-input" >
                       <label for="phone" class="laple-forms"><?php echo $lang['item27']?> </label>
						<input class="input100" type="text" name="phone"  value='<?php if(isset($_POST['phone']))echo$_POST['phone']; else echo $this->view_data['editeProfile'][2]['value'];?>'  oninput="phonenumber(document.signupForm.phone)">
						<span class="text-danger text-error" id="phoneError"> </span>
					</div>

					<div class="wrap-input100 validate-input" >
                         <label for="bio" class="laple-forms"><?php echo $lang['item132']?> </label>
                        <textarea  class="input100"  name="bio" placeholder="<?php echo $lang['item133']?>" oninput="preventSpace(document.editFormProfile.bio,2,30);" >
                        <?php if(isset($_POST['Bio']))echo$_POST['bio']; elseif(isset($this->view_data['editeProfile'][3])) echo $this->view_data['editeProfile'][3]['value']; ?>
                     </textarea>
						<span class="text-danger text-error" id="bioError"> </span>
					</div>
					<div class="singup-mainb-tn" >
						<div class="wrap-login100-form-btn">
							<div class="login100-form-bgbtn"></div>
							<button class="login100-form-btn" id="signuptBtn" onclick="editprofileinfo()">
							<?php echo $lang['item131']?>
							</button>
						</div>
					</div>
				
				</form>
			</div>
		</div>

	</section>   
<!-- profile page end -->

<script>



function editprofileinfo(){
    if(Requirevalidation(document.editFormProfile.first_name)&&Requirevalidation(document.editFormProfile.last_name)
        &&Requirevalidation(document.editFormProfile.phone)){

        jQuery_1_3_2.ajax({
            url:"/editeProfile",
            method:"POST",
            data:{method:"editProfile",
            formData: jQuery_1_3_2("#editFormProfile").serialize(),
            },
            success:function(data)
            {
              var result=JSON.parse(data);
              if(result.statusCode=='200'){
                window.location.href = '/profile/index';

              }

          }
      });
    }
          
      }
</script>

<?php  include  VIEW.'layouts'.DIRECTORY_SEPARATOR.'footer_section.phtml' ?>
<?php  include  VIEW.'layouts'.DIRECTORY_SEPARATOR.'footer.phtml' ?>
