<?php

  include  VIEW.'layouts'.DIRECTORY_SEPARATOR.'header.phtml'; ?>
    <!-- start pages photo -->
    <section class="cover-background top-space" style="background-image:url('/images/home/1(1).jpg');">
        <div class="opacity-medium bg-dark"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12 display-table page-title">
                    <div class="vertical-align-middle text-center">
                        <!-- start sub title -->
                        <span class="text-white">Profile</span>
                        <!-- end sub title -->
                        <!-- start page title -->
                        <h1 class="text-white">Welcome to My Profile</h1>
                        <!-- end page title -->
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- end pages photo - -->

    <!-- profile page start-->
<div class="main main-raised border-50">
    <div class="profile-content">
        <div class="container">
            <div class="row">
			    <div class="col-md-12 col-xs-12 ml-auto mr-auto mt-80">
					<div class="tab-content" id="myTabContent">
						     <form class="" action="" method="post" name="editFormProfile" id="editFormProfile" enctype="multipart/form-data">
								<div class="row register-form ">
                                        <!-- PROFILE PHOTO -->
                                        <div class="col-md-12 col-xs-12 ml-auto mr-auto">
                                            <div class="profile">
                                                <div class="text-center mt-50px">
                                                    <div class="profile-img-size circle">
                                                    <img src="/images/home/user.jpg" alt="Circle Image" class="img-raised rounded-circle img-fluid profile-pic" width="auto">
                                                    
                                                    <i class="fas fa-user-edit upload-button p-image-edit"></i>
                                                    <input class="file-upload" type="file" accept="image/*"/> 

                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <!-- PROFILE PHOTO -->
                                                            
								<div class="col-md-6 mt-80">
										<div class="form-group">
											<label for="first_name" class="laple-forms">Your First Name</label>
											<input type="text" class="form-control" placeholder="First Name *"  name="first_name" value='<?php if(isset($_POST['first_name']))echo$_POST['first_name']; else echo $this->view_data['editeProfile'][0]['value'];?>' oninput=" stringlength(document.editFormProfile.first_name,5,12); allLetter(document.editFormProfile.first_name);preventSpace(document.editFormProfile.first_name,0,0)" />
										<?php echo Message::check('first_name');?>
										<span class="text-danger text-error" id="first_nameError"> </span>
										</div>
										<div class="form-group">
											<label for="last_name" class="laple-forms">Your Last Name</label>
											<input type="text" class="form-control" placeholder="Last Name *" name="last_name" value='<?php if(isset($_POST['last_name']))echo$_POST['last_name']; else echo $this->view_data['editeProfile'][1]['value'];?>' oninput=" stringlength(document.editFormProfile.last_name,5,12); allLetter(document.editFormProfile.last_name);preventSpace(document.editFormProfile.first_name,0,0)" />
											<?php echo Message::check('last_name');?>
											<span class="text-danger text-error" id="last_nameError"> </span>
                                        </div>
                                        <div class="form-group">
											<label for="phone" class="laple-forms">Your Phone</label>
											<input type="text"  name="phone" class="form-control" placeholder="Your Phone *" value='<?php if(isset($_POST['phone']))echo$_POST['phone']; else echo $this->view_data['editeProfile'][2]['value'];?>' oninput="phonenumber(document.editFormProfile.phone)"; />
											<?php echo Message::check('phone');?>
											<span class="text-danger text-error" id="phoneError"> </span>
										</div>
								</div>		
								<div class="col-md-6 mt-80">
										<div class="form-group">
											<label for="Gender" class="laple-forms">Gender</label>
											<select type="text"  name="Gender" class="form-control" value=''>
                                                <option value="Female">Female</option>
                                                <option value="male">male</option>
                                            </select>
                                        </div>
                                        <div class="form-group">
											<label for="date" class="laple-forms">Birth Day</label>
											<input type="date"  name="date" class="form-control" placeholder="Your Birthday" value='' />
                                        </div>
                                        <div class="form-group">
											<label for="bio" class="laple-forms">Bio</label>
                                            <textarea  rows="4" cols="50" type="text"  name="bio" class="form-control" placeholder="Your Bio" oninput="preventSpace(document.editFormProfile.bio,5,30);"></textarea>
											<span class="text-danger text-error" id="bioError"> </span>
                                            
                                        </div>
                                </div>
                                            </div>
                                        <center>
										<input id="editBtn" type="submit" class="btnEdit float-none" onclick="" value="Edit"/>
										</center>
										</div>
					         </form>     
				</div>
                <!-- PROFILE PHOTO -->
            </div>  
        </div>
    </div>
</div>
      
<!-- profile page end -->

<script>

$(document).ready(function(){
    $("#editBtn").click(function(){  
		event.preventDefault();  
        if(Requirevalidation(document.editFormProfile.first_name)&&Requirevalidation(document.editFormProfile.last_name)
        &&Requirevalidation(document.editFormProfile.phone)){
			serverSideValidate()
		
			
		}    
    });
});


function serverSideValidate(){
	
    $.ajax({
                url:"/validate",
                method:"POST",
                 data:{
                     type:"editProfile",
                     formData:$('#editFormProfile').serialize()}
                     ,
                success:function(data)
                {
            var result=JSON.parse(data);
        
            if(result.statusCode==200){
    
                $("#editFormProfile").submit(); // Submit the form
            }
            else{
                    var error=JSON.parse(result.message);
                    $.each( error, function( key, value ) {
                        if(key=='msgState' || key=='main');
                        else
                        document.getElementById(key+'Error').innerHTML=value;
    
                        });
                        return false;
    
                }
          }
    
            
                   });
                }
</script>

<?php  include  VIEW.'layouts'.DIRECTORY_SEPARATOR.'footer.phtml' ?>
