<?php include  VIEW.'layouts'.DIRECTORY_SEPARATOR.'head.phtml';?>
<body class="bg-blue">
<div class="container error-form">
    <div class="row">
        <div class="col-md-12 register-left">
                <div class="animation-ttp">
                <a href="/home/index">
                    <img src="/images/home/logo.png" alt=""/>
                </a>
                </div>
                <div class="p-5">
                <h1><span class="text-white text-size-4em ">4</span><span class="text-white text-size-4em ">0</span><span class="text-white text-size-4em ">4</span> <span class="text-blue text-size-4em "></span>!</h1>
                <p><?php echo $lang['item90'] ?>!</p>
                <h3></h3>
                <p class="p-login nots-p-reg"><?php echo $lang['item91'] ?> <a href="/home/index">Home!</a></p>

                </div>
            
        </div>
    </div>
</div>
   
       <!-- <script>
         setTimeout(function(){
            window.location.href = '/home/index';
         }, 2000);
      </script> -->


