<?php
  include  VIEW.'layouts'.DIRECTORY_SEPARATOR.'header.phtml';
  ?>

<body>

  <!-- start pages photo -->
  <section class="cover-background top-space" style="background-image:url('/images/home/wbg.jpg')">
        <div class="opacity-medium bg-purple"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12 display-table page-title">
                    <div class="vertical-align-middle text-center">
                        <!-- start sub title -->
                        <h1 class="text-white text-shadow-black">FAQS</h1>
                        <!-- end sub title -->
                        <!-- start page title -->
                        <!-- <h1 class="text-white text-shadow-black"><?php echo $lang['item31']?></h1> -->
                        <!-- end page title -->
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- end pages photo - -->


    <div class="container container-faq col-lg-12 col-sm-12 col-xs-12 col-md-12">

<h2 class="h2-faq">Frequently Asked Questions</h2>

<div class="accordion">
  <div class="accordion-item">
    <a>How I can Add my Campagin?<i class="fas fa-plus"></i></a>
    <div class="content">
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Elementum sagittis vitae et leo duis ut. Ut tortor pretium viverra suspendisse potenti.</p>
    </div>
  </div>
  <div class="accordion-item">
    <a>How donate for me?<i class="fas fa-plus"></i></a>
    <div class="content">
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Elementum sagittis vitae et leo duis ut. Ut tortor pretium viverra suspendisse potenti.</p>
    </div>
  </div>
  <div class="accordion-item">
    <a>How can i Get my Money<i class="fas fa-plus"></i></a>
    <div class="content">
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Elementum sagittis vitae et leo duis ut. Ut tortor pretium viverra suspendisse potenti.</p>
    </div>
  </div>
  <!-- <div class="accordion-item">
    <a>How much does the Earth weigh?<i class="fas fa-plus"></i></a>
    <div class="content">
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Elementum sagittis vitae et leo duis ut. Ut tortor pretium viverra suspendisse potenti.</p>
    </div>
  </div>
  <div class="accordion-item">
    <a>How do airplanes stay up?<i class="fas fa-plus"></i></a>
    <div class="content">
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Elementum sagittis vitae et leo duis ut. Ut tortor pretium viverra suspendisse potenti.</p>
    </div>
  </div> -->
</div>

</div>
    <?php include  VIEW.'layouts'.DIRECTORY_SEPARATOR.'footer_section.phtml'; ?>
    <?php include  VIEW.'layouts'.DIRECTORY_SEPARATOR.'footer.phtml'; ?>

