<?php

include VIEW.'layouts'.DIRECTORY_SEPARATOR.'header.phtml';

 ?>
   <body>
    <!-- start slider -->
    <section id="slider">
            <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
                    <!-- <ol class="carousel-indicators">
                      <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
                      <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
                      <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
                    </ol> -->
                    <div class="carousel-inner">
                      <div class="carousel-item bg-black active">
                        <img src="/images/home/1(1).jpg" class="d-block w-100 opacity-5" alt="...">
                        <div class="carousel-caption d-none d-md-block">
                          <h1 class="h1-slide wow fadeIn">Fundraising for the people and <br>
                              causes you care about</h1>
                          <p class="wow fadeInUp p-slide" data-wow-delay="0.5s">You Can Start Now!</p>
                          <button type="button" class="btn btn-blue wow flipInX btn-big" data-wow-delay="0.9s">Start a fund Me</button>
                        </div>
                      </div>
                      <div class="carousel-item bg-black">
                        <img src="/images/home/1(2).jpg" class="d-block w-100 opacity-5" alt="...">
                        <div class="carousel-caption d-none d-md-block">
                          <h1 class="h1-slide wow fadeIn">Fundraising for the people and <br>
                            causes you care about</h1>
                          <p class="wow fadeInUp p-slide" data-wow-delay="0.5s">You Can Start Now!</p>
                          <button type="button" class="btn btn-blue wow flipInX btn-big" data-wow-delay="0.9s">Start a fund Me</button>
                        </div>
                      </div>
                      <div class="carousel-item bg-black">
                        <img src="/images/home/1(5).jpg" class="d-block w-100 opacity-5" alt="...">
                        <div class="carousel-caption d-none d-md-block">
                          <h1 class="h1-slide wow fadeIn">Fundraising for the people and <br>
                             causes you care about</h1>
                          <p class="wow fadeInUp p-slide" data-wow-delay="0.5s">You Can Start Now!</p>

                          <button type="button" class="btn btn-blue wow flipInX btn-big" data-wow-delay="0.9s">Start a fund Me</button>
                        </div>
                      </div>
                      <div class="carousel-item bg-black">
                        <img src="/images/home/1(4).jpg" class="d-block w-100 opacity-5" alt="...">
                        <div class="carousel-caption d-none d-md-block">
                          <h1 class="h1-slide wow fadeIn">Fundraising for the people and <br>
                               causes you care about</h1>
                          <p class="wow fadeInUp p-slide" data-wow-delay="0.5s">You Can Start Now!</p>
                          <button type="button" class="btn btn-blue wow flipInX btn-big" data-wow-delay="0.9s">Start a fund Me</button>
                        </div>
                      </div>
                      <a href="#numone" class="animation-ttp icon-home-arrow demo"><i class="fas fa-angle-down"></i></a>

                    </div>

            </div>
    </section>
    <!-- end slider -->




     <!-- service start -->
     <section id="numone" class="wow fadeIn p-section" style="visibility: visible; animation-name: fadeIn;">
     <center>
       <h2 class="title-home">Our Services</h2>
     </center>
        <div class="container">
            <div class="row">
                <!-- start feature box item -->
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 feature-box-1 xs-margin-30px-bottom wow fadeIn last-paragraph-no-margin" style="visibility: visible; animation-name: fadeIn;">
                    <div class="col-md-12 col-sm-12 no-padding margin-15px-bottom alt-font">
                        <h3 class="char-value text-blue letter-spacing-minus-1 font-weight-600 servic-num">01.</h3>
                        <span class="text-large text-extra-dark-gray line-height-22 padding-20px-left sm-padding-15px width-100 display-table-cell vertical-align-middle text-size-22px">Help You.<br>Achived Your Goal.</span>
                    </div>
                    <p class="width-90 sm-width-100">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since. Lorem Ipsum has been the industry.</p>
                </div>
                <!-- end feature box item -->
                <!-- start feature box item -->
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 feature-box-1 xs-margin-30px-bottom wow fadeIn last-paragraph-no-margin" data-wow-delay="0.2s" style="visibility: visible; animation-delay: 0.2s; animation-name: fadeIn;">
                    <div class="col-md-12 col-sm-12 no-padding margin-15px-bottom alt-font">
                        <h3 class="char-value text-blue letter-spacing-minus-1 font-weight-600 servic-num">02.</h3>
                        <span class="text-large text-extra-dark-gray line-height-22 padding-20px-left width-100 display-table-cell vertical-align-middle text-size-22px">Help You.<br>Achived Your Goal.</span>
                    </div>
                    <p class="width-90 sm-width-100">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since. Lorem Ipsum has been the industry.</p>
                </div>
                <!-- end feature box item -->
                <!-- start feature box item -->
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 feature-box-1 wow fadeIn last-paragraph-no-margin" data-wow-delay="0.4s" style="visibility: visible; animation-delay: 0.4s; animation-name: fadeIn;">
                    <div class="col-md-12 col-sm-12 no-padding margin-15px-bottom alt-font">
                        <h3 class="char-value text-blue letter-spacing-minus-1 font-weight-600 servic-num">03.</h3>
                        <span class="text-large text-extra-dark-gray line-height-22 padding-20px-left width-100 display-table-cell vertical-align-middle text-size-22px">Help You.<br>Achived Your Goal.</span>
                    </div>
                    <p class="width-90 sm-width-100">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since. Lorem Ipsum has been the industry.</p>
                </div>
                <!-- end feature box item -->
            </div>
        </div>
    </section>
    <!-- service start -->

<!-- service start -->
<section id="compignhome" class="bg-blue p-section">

<h1 class="text-center text-white text-fantasy">Fund Me</h1>
<h1 class="text-center text-white">we'll always support you </h1>
<center>
<button type="button" class="btn btn-blue">Start a fund Me</button>

</center>
</section>
<!-- service end -->

<!-- latest compign -->
<section class="p-section">
    <center>
      <h2 class="title-home">The Last Compagin</h2>
    </center>
    <div class="container">
    <!-- <div class="row"> -->
    <div class="tab-pane text-center mx-auto gallery" id="works">

              <div class="row" id="active-compain">

              </div>


              <a href="/compaign" class="btn btn-white"><span style="font-size: 30px"></span>  Read More</a>

      </div>
    </div>

    </div>
</section>
<!-- latest Compaign -->



<script>

function load_data(){

  var loading="<button class='btn btn-primary' disabled><span class='spinner-border spinner-border-sm'></span>Loading..</button>";
  var err="<h1>ther is error pleas try agin</h2>";
		jQuery_1_3_2.ajax({

			url:"/managecompaign",
			method:"POST",
      data:{type:"2"},
      beforeSend:function () {
        jQuery_1_3_2('#active-compain').html(loading);
      },
      timeout: 10000,
			success:function(data)
			{
        html='';
        var userInfo=JSON.parse(data);
        // alert(d)

        jQuery_1_3_2.each( userInfo.data, function( index, row ) {
        html+=' <div class="col-md-4 img-overlay">'+
                  '<div class="card">'+
                      '<img class="card-img-top" src="/uploads/'+row.galary+'" alt="Card image cap">'+
                      '<div class="overlay">'+
                      '<div class="text-overlay"> '+
                        '<h5 class="card-title">compagin</h5>'+
                        '<p class="card-text">'+row.title+'</p>'+
                        '<a href="/viewCompaign/show/'+row.id+'" class="btn btn-home-comp">Go somewhere</a>'+
                      '</div>'+
                      '</div>'+
                  '</div>'+
              '</div>';
      });
      jQuery_1_3_2('#active-compain').html(html);

    },
    statusCode:{
      404:function () {
        jQuery_1_3_2('#active-compain').html(err);
      }
    },
    error:function (xhr,textStatus,errorThrown) {
      if (textStatus=='timeout') {
        jQuery_1_3_2('#active-compain').html(err);

      }
     }


		       });
}
jQuery_1_3_2(document).ready(function(){
         load_data();
  });

</script>

<?php  include VIEW.'layouts'.DIRECTORY_SEPARATOR.'footer.phtml' ?>
