<?php

include VIEW.'layouts'.DIRECTORY_SEPARATOR.'header.phtml'; ?>
   
    <!-- start slider -->
    <section id="slider">
            <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
                    <!-- <ol class="carousel-indicators">
                      <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
                      <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
                      <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
                    </ol> -->
                    <div class="carousel-inner">
                      <div class="carousel-item bg-black active">
                        <img src="/images/home/1(1).jpg" class="d-block w-100 opacity-5" alt="...">
                        <div class="carousel-caption d-none d-md-block">
                          <h1 class="h1-slide wow fadeIn">Fundraising for the people and <br>
                              causes you care about</h1>
                          <p class="wow fadeInUp p-slide" data-wow-delay="0.5s">You Can Start Now!</p>
                          <button type="button" class="btn btn-blue wow flipInX" data-wow-delay="0.9s">Start a Found Me</button>
                        </div>
                      </div>
                      <div class="carousel-item bg-black">
                        <img src="/images/home/1(2).jpg" class="d-block w-100 opacity-5" alt="...">
                        <div class="carousel-caption d-none d-md-block">
                          <h1 class="h1-slide wow fadeIn">Fundraising for the people and <br>
                            causes you care about</h1>
                          <p class="wow fadeInUp p-slide" data-wow-delay="0.5s">You Can Start Now!</p>
                          <button type="button" class="btn btn-blue wow flipInX" data-wow-delay="0.9s">Start a Found Me</button>
                        </div>
                      </div>
                      <div class="carousel-item bg-black">
                        <img src="/images/home/1(5).jpg" class="d-block w-100 opacity-5" alt="...">
                        <div class="carousel-caption d-none d-md-block">
                          <h1 class="h1-slide wow fadeIn">Fundraising for the people and <br>
                             causes you care about</h1>
                          <p class="wow fadeInUp p-slide" data-wow-delay="0.5s">You Can Start Now!</p>
                          <button type="button" class="btn btn-blue wow flipInX" data-wow-delay="0.9s">Start a Found Me</button>
                        </div>
                      </div>
                      <div class="carousel-item bg-black">
                        <img src="/images/home/1(4).jpg" class="d-block w-100 opacity-5" alt="...">
                        <div class="carousel-caption d-none d-md-block">
                          <h1 class="h1-slide wow fadeIn">Fundraising for the people and <br>
                               causes you care about</h1>
                          <p class="wow fadeInUp p-slide" data-wow-delay="0.5s">You Can Start Now!</p>
                          <button type="button" class="btn btn-blue wow flipInX" data-wow-delay="0.9s">Start a Found Me</button>
                        </div>
                      </div>
                      <section class="demo">
                      <a href="#numone"><span></span>^</a>
                      </section>

                    </div>

            </div>
    </section>
    <!-- end slider -->


  

     <!-- service start -->
     <section id="numone" class="wow fadeIn p-section" style="visibility: visible; animation-name: fadeIn;">
        <div class="container">
            <div class="row">
                <!-- start feature box item -->
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 feature-box-1 xs-margin-30px-bottom wow fadeIn last-paragraph-no-margin" style="visibility: visible; animation-name: fadeIn;">
                    <div class="col-md-12 col-sm-12 no-padding margin-15px-bottom alt-font">
                        <h3 class="char-value text-blue letter-spacing-minus-1 font-weight-600 servic-num">01.</h3>
                        <span class="text-large text-extra-dark-gray line-height-22 padding-20px-left sm-padding-15px width-100 display-table-cell vertical-align-middle text-size-22px">Creativity.<br> Discover talent.</span>
                    </div>
                    <p class="width-90 sm-width-100">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since. Lorem Ipsum has been the industry.</p>
                </div>
                <!-- end feature box item -->
                <!-- start feature box item -->
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 feature-box-1 xs-margin-30px-bottom wow fadeIn last-paragraph-no-margin" data-wow-delay="0.2s" style="visibility: visible; animation-delay: 0.2s; animation-name: fadeIn;">
                    <div class="col-md-12 col-sm-12 no-padding margin-15px-bottom alt-font">
                        <h3 class="char-value text-blue letter-spacing-minus-1 font-weight-600 servic-num">02.</h3>
                        <span class="text-large text-extra-dark-gray line-height-22 padding-20px-left width-100 display-table-cell vertical-align-middle text-size-22px">Technology.<br> Expert analysis.</span>
                    </div>
                    <p class="width-90 sm-width-100">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since. Lorem Ipsum has been the industry.</p>
                </div>
                <!-- end feature box item -->
                <!-- start feature box item -->
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 feature-box-1 wow fadeIn last-paragraph-no-margin" data-wow-delay="0.4s" style="visibility: visible; animation-delay: 0.4s; animation-name: fadeIn;">
                    <div class="col-md-12 col-sm-12 no-padding margin-15px-bottom alt-font">
                        <h3 class="char-value text-blue letter-spacing-minus-1 font-weight-600 servic-num">03.</h3>
                        <span class="text-large text-extra-dark-gray line-height-22 padding-20px-left width-100 display-table-cell vertical-align-middle text-size-22px">Discover.<br> Explore work.</span>
                    </div>
                    <p class="width-90 sm-width-100">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since. Lorem Ipsum has been the industry.</p>
                </div>
                <!-- end feature box item -->
            </div>
        </div>
    </section>
    <!-- service start -->


<?php  include VIEW.'layouts'.DIRECTORY_SEPARATOR.'footer.phtml' ?>
