<?php

include VIEW.'layouts'.DIRECTORY_SEPARATOR.'header.phtml'; ?>
<body>
    <!-- start slider -->
    <section id="slider">
            <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
                    <ol class="carousel-indicators">
                      <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
                      <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
                      <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
                    </ol>
                    <div class="carousel-inner">
                      <div class="carousel-item bg-black active">
                        <img src="/images/home/1(1).jpg" class="d-block w-100 opacity-5" alt="...">
                        <div class="carousel-caption d-none d-md-block">
                          <h1 class="margin-b-slide">First slide label</h1>
                          <p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
                          <button type="button" class="btn btn-blue">Light</button>
                        </div>
                      </div>
                      <div class="carousel-item bg-black">
                        <img src="/images/home/1(2).jpg" class="d-block w-100 opacity-5" alt="...">
                        <div class="carousel-caption d-none d-md-block">
                          <h5 class="margin-b-slide">Second slide label</h5>
                          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                          <button type="button" class="btn btn-blue">Light</button>
                        </div>
                      </div>
                      <div class="carousel-item bg-black">
                        <img src="/images/home/1(3).jpg" class="d-block w-100 opacity-5" alt="...">
                        <div class="carousel-caption d-none d-md-block">
                          <h5 class="margin-b-slide">Third slide label</h5>
                          <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur.</p>
                          <button type="button" class="btn btn-blue">Light</button>
                        </div>
                      </div>
                      <div class="carousel-item bg-black">
                        <img src="/images/home/1(4).jpg" class="d-block w-100 opacity-5" alt="...">
                        <div class="carousel-caption d-none d-md-block">
                           <h5 class="margin-b-slide">Third slide label</h5>
                           <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur.</p>
                           <button type="button" class="btn btn-blue">Light</button>
                        </div>
                      </div>
                    </div>
            </div>
    </section>
    <!-- end slider -->

<?php  include VIEW.'layouts'.DIRECTORY_SEPARATOR.'footer.phtml' ?>
