<?php   include VIEW.'layouts'.DIRECTORY_SEPARATOR.'head.phtml' ?>

<!-- start login -->
<body class="bg-blue">

<section>
			<div class="container register">
					<div class="row">
						<div class="col-md-12 register-left">
								<a href="/home/index">
									<img src="/images/home/logo.png" alt=""/>
								</a>
							<h3><?php echo $lang['item10']?></h3>
							<p class="p-login nots-p-reg"><?php echo $lang['item11']?> <a href="/auth/signup"><?php echo $lang['item4b']?></a></p>
						</div>
						<div class="col-md-12 register-right shadow-div">
						<form class="" action="" method="post" name="loginForm" id="loginForm">

							<div class="tab-content" id="myTabContent">
								<div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
									<h3 class="register-heading"><?php echo $lang['item4a']?></h3>
									<div class="row register-form">
									<div class="col-md-12">
											<div class="form-group">
												<label for="email" class="laple-forms"><?php echo $lang['item12']?></label>
												<input type="email" name="email" class="form-control" placeholder="<?php echo $lang['item12']?> *" value='<?php if(isset($_POST['email']))echo$_POST['email'];?>' />
												
											</div>
											
											<div class="form-group">
												<label for="password" class="laple-forms"><?php echo $lang['item13']?></label>
												<input type="password" name="password" class="form-control" placeholder="<?php echo $lang['item13']?> *" value='<?php if(isset($_POST['email']))echo$_POST['email'];?>' />
												<span class="text-danger text-error" id="passwordError"> </span>

											</div>
										</div>
										<div class="col-md-12">
											<center>
											<!-- <input type="submit" class="btnRegister"  value="Log In"/> -->
											<input type="submit" id="logintBtn" class="btnlogin float-none"  value="Log In"/>
											<p class="p-login-forget"><?php echo $lang['item14']?> ! <a href="/auth/forgetPass"><?php echo $lang['item15']?> </a></p>
											</center>
										</div>
									</div>
								</div>
</form>
							</div>
						</div>
					</div>

				</div>
    </section>
	<script>
$(document).ready(function(){
    $("#logintBtn").click(function(){
		event.preventDefault();
		 if(Requirevalidation(document.loginForm.email)&&Requirevalidation(document.loginForm.password))
		serverSideValidate();

    });
});


function serverSideValidate(){

	jQuery_1_3_2.ajax({
				url:"/validate",
				method:"POST",
				 data:{
					 type:"login",
					 formData:$('#loginForm').serialize()
					}
					 ,
				success:function(data)
				{
			var result=JSON.parse(data);

			if(result.statusCode==200){

				$("#loginForm").submit(); // Submit the form
			}
			else{
					var error=JSON.parse(result.message);
					$.each( error, function( key, value ) {
						if(key=='msgState' || key=='main');
						else
						document.getElementById(key+'Error').innerHTML="<i class='fas fa-exclamation-circle error-icon'></i>"+value;

						});
						return false;
				}
		  }

				   });
				}
</script>

    <!-- end login -->
<?php  include VIEW.'layouts'.DIRECTORY_SEPARATOR.'footer.phtml' ?>
