<?php   include VIEW.'layouts'.DIRECTORY_SEPARATOR.'head.phtml' ?>

<!-- start login -->

<section>
			<div class="container register">
					<div class="row">
						<div class="col-md-12 register-left">
								<a href="home.html">
									<img src="/images/home/logo.png" alt=""/>
								</a>
							
							<h3>Welcome</h3>
							<p class="p-login nots-p-reg">You don't have account! <a href="/auth/signup">SignUp</a></p>
						</div>
						<div class="col-md-12 register-right shadow-div">
							
							<div class="tab-content" id="myTabContent">
								<div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
									<h3 class="register-heading">Log IN</h3>
									<div class="row register-form wow  flipInX">
										<div class="col-md-12">
											<div class="form-group">
												<input type="email" class="form-control" placeholder="Your Email *" value="" />
											</div>
											<div class="form-group">
												<input type="password" class="form-control" placeholder="Password *" value="" />
											</div>
											
											
										</div>
										<div class="col-md-12">
											<center>
											<input type="submit" class="btnlogin float-none"  value="Log In"/>
											<p class="p-login-forget">forgot your password ! <a href="login.html">Forgot</a></p>
											</center>
										</div>
									</div>
								</div>
							
							</div>
						</div>
					</div>
	
				</div>
    </section>


    <!-- end login -->
<?php  include VIEW.'layouts'.DIRECTORY_SEPARATOR.'footer.phtml' ?>
