<?php 

if(Session::logged())
  header('location:/home/index');
include VIEW.'layouts'.DIRECTORY_SEPARATOR.'head.phtml' ?>

<!-- start login -->

<div class="container-fulid login-background">

	

<section class="">
		<div class="container-login100">
			<div class="wrap-login100">
				<form class="login100-form validate-form"  action="" method="post"  name="loginForm" id="loginForm">
					<span class="login100-form-title p-b-26">
					<?php echo $lang['item10']?>
					</span>
					<span class="login100-form-title p-b-48">
					<a href="/home/index">
									<img src="/images/home/fundmee.png" class='logoo' alt=""/>
								</a>
					</span>

					<div class="wrap-input100 validate-input" data-validate = "Valid email is: a@b.c">
						<input class="input100" type="text" name="email"  value='<?php if(isset($_POST['email']))echo$_POST['email'];?>' />
						<span class="focus-input100" data-placeholder="<?php echo $lang['item12']?>"></span>
						<span class="text-danger text-error" id="emailError"> </span>
					</div>

					<div class="wrap-input100 validate-input" data-validate="Enter password">
						<span class="btn-show-pass">
							<i class="fas fa-eye"></i>
						</span>
						<input class="input100" type="password" name="password"  value='<?php if(isset($_POST['password']))echo$_POST['password'];?>'>
						<span class="focus-input100" data-placeholder="<?php echo $lang['item13']?>"></span>
						<span class="text-danger text-error" id="passwordError"> </span>
					</div>

					<div class="mainbtn" >
						<div class="wrap-login100-form-btn">
							<div class="login100-form-bgbtn"></div>
							<button class="login100-form-btn" id="logintBtn">
								Login
							</button>
						</div>
					</div>
					<div class="extra" >
						
							
					<span class="txt1">
					<?php echo $lang['item11']?>
						</span>

						<a class="txt2" href="/auth/signup">
						<?php echo $lang['item4b']?>
						</a>						
					</div>
					<br>
					<br>
					<br>					
						<a class="txt3" href="/auth/forgetPass" >
						<?php echo $lang['item14']?>
						</a>
					<!-- </div> -->
				</form>
			</div>
		</div>
	</div>
	

			</div>
</section>
			
		</div>
		

	
	

</div>
	<script>
$(document).ready(function(){
    $("#logintBtn").click(function(){
		event.preventDefault();
		 if(Requirevalidation(document.loginForm.email)&&Requirevalidation(document.loginForm.password))
		serverSideValidate();

    });
});


function serverSideValidate(){

	jQuery_1_3_2.ajax({
				url:"/validate",
				method:"POST",
				 data:{
					 type:"login",
					 formData:$('#loginForm').serialize()
					}
					 ,
				success:function(data)
				{
			var result=JSON.parse(data);

			if(result.statusCode==200){

				$("#loginForm").submit(); // Submit the form
			}
			else{
					var error=JSON.parse(result.message);
					$.each( error, function( key, value ) {
						if(key=='msgState' || key=='main');
						else
						document.getElementById(key+'Error').innerHTML="<i class='fas fa-exclamation-circle error-icon'></i>"+value;

						});
						return false;
				}
		  }

				   });
				}
</script>

    <!-- end login -->
<?php  include VIEW.'layouts'.DIRECTORY_SEPARATOR.'footer.phtml' ?>
