<?php   include VIEW.'layouts'.DIRECTORY_SEPARATOR.'head.phtml' ?>

<!-- start login -->
<body class="bg-blue">

<section>
			<div class="container register">
					<div class="row">
						<div class="col-md-12 register-left">
								<a href="/home/index">
									<img src="/images/home/logo.png" alt=""/>
								</a>
							<h3>Welcome</h3>
							<p class="p-login nots-p-reg">You don't have account! <a href="/auth/signup">SignUp</a></p>
						</div>
						<div class="col-md-12 register-right shadow-div">
						<form class="" action="" method="post" name="loginForm">

							<div class="tab-content" id="myTabContent">
								<div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
									<h3 class="register-heading">Log IN</h3>
									<div class="row register-form wow  flipInX">
									<div class="col-md-12">
											<div class="form-group">
												<label for="email" class="laple-forms">Your Email</label>
												<input type="email" name="email" class="form-control" placeholder="Your Email *" value="" />
												<?php echo Message::check('email');  ?>
											</div>
											<div class="form-group">
												<label for="password" class="laple-forms">Your password</label>
												<input type="password" name="password" class="form-control" placeholder="Password *" value="" />
												<?php echo Message::check('password');  ?>
											</div>
										</div>
										<div class="col-md-12">
											<center>
											<!-- <input type="submit" class="btnRegister"  value="Log In"/> -->
											<input type="submit" class="btnlogin float-none"  value="Log In"/>
											<p class="p-login-forget">forgot your password ! <a href="login.html">Forgot</a></p>
											</center>
										</div>
									</div>
								</div>
</form>
							</div>
						</div>
					</div>

				</div>
    </section>


    <!-- end login -->
<?php  include VIEW.'layouts'.DIRECTORY_SEPARATOR.'footer.phtml' ?>
