<?php

  include  VIEW.'layouts'.DIRECTORY_SEPARATOR.'head.phtml'; ?>
<!-- Modals -->
<body>
    <!-- start pages photo -->
    <section class="cover-background top-space" style="background-image:url('/images/home/1(1).jpg');">
        <div class="opacity-medium bg-gray"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12 display-table page-title">
                    <div class="vertical-align-middle text-center">
                        <!-- start sub title -->
                        <!-- <span class="text-white text-shadow-black">Profile</span> -->
                        <!-- end sub title -->
                        <!-- start page title -->
                        <!-- <h1 class="text-white text-shadow-black">Welcome to My Profile</h1> -->
                        <!-- end page title -->
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- end pages photo - -->

    <!-- profile page start-->
    <div class="main main-raised border-50">
		<div class="profile-content">
            <div class="container">
                <div class="row">
	                <div class="col-md-6 ml-auto mr-auto">
        	           <div class="profile">
	                        <div class="text-center mt-50px circle">
	                            <img src="/images/home/profile4.jpg" alt="Circle Image" class="img-raised rounded-circle img-fluid profile-pic" width="250px";>
                          </div>
                          <div class="p-image">
                            <img class="upload-button" src="/images/home/edit.png" alt="">
                               <input class="file-upload" type="file" accept="image/*"/>
                            </div>
	                        <div class="name text-center">
	                            <h3 class="title"><?php echo $this->view_data['username']; ?></h3>
                                <h6>Designer</h6>
                                <a href="#pablo" class="btn btn-just-icon btn-link btn-dribbble"><i class="fa fa-dribbble"></i></a>
                                <a href="#pablo" class="btn btn-just-icon btn-link btn-twitter"><i class="fa fa-twitter"></i></a>
                                <a href="#pablo" class="btn btn-just-icon btn-link btn-pinterest"><i class="fa fa-pinterest"></i></a>
	                        </div>
	                    </div>
    	            </div>
                </div>

				<div class="row">
					<div class="col-md-6 ml-auto mr-auto">
                        <div class="profile-tabs">
                          <ul class="nav nav-pills nav-pills-icons justify-content-center" role="tablist">
                            <li class="nav-item">
                                <a class="nav-link active" href="#studio" role="tab" data-toggle="tab">
                                 About
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#works" role="tab" data-toggle="tab">
                                 Compigan
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#favorite" role="tab" data-toggle="tab">
                                  Donition
                                </a>
                            </li>
                          </ul>
                        </div>
    	    	</div>
            </div>

          <div class="tab-content tab-space">
            <div class="tab-pane active text-center gallery" id="studio">
                <div class="row">
                    <div class="description text-center">
                        <div class="container text-center">
                          <div class="row text-center">
                            <?php
                             if (array_key_exists('profiles',$this->view_data)){
                              $html='';
                              foreach ($this->view_data['profiles'] as $profile) {
                                      $html.='<div class="col-md-6">';
                                        $html.=$profile['name'];
                                  $html.='</div>  <div class="col-md-6">';
                                        $html.=$profile['value'];
                                      $html.='</div>';
                              }
                            echo $html;
                            }
                              ?>
                          </div>
                        </div>
                      </div>
                </div>
  			</div>
            <div class="tab-pane text-center gallery" id="works">
                <div class="row">
                    <div class="col-md-6">
                        <div class="card" style="width: 18rem;">
                            <img class="card-img-top" src="..." alt="Card image cap">
                            <div class="card-body">
                              <h5 class="card-title">Card title</h5>
                              <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                              <a href="#" class="btn btn-primary">Go somewhere</a>
                            </div>
                          </div>
                    </div>
                  </div>
  			</div>
            <div class="tab-pane text-center gallery" id="favorite">
                <div class="row">
                    <div class="col-md-6">
                        <div class="card" style="width: 18rem;">
                            <img class="card-img-top" src="..." alt="Card image cap">
                            <div class="card-body">
                              <h5 class="card-title">Card title</h5>
                              <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                              <a href="#" class="btn btn-primary">Go somewhere</a>
                            </div>
                          </div>
                    </div>
                  </div>
      		</div>
          </div>


            </div>
        </div>
	</div>
	<!-- profile page end -->



<script src="/js/home/jquery-3.4.1.slim.min.js"></script>
<script src="/js/home/js.js"></script>
<script src="/js/home/popper.min.js"></script>
<script src="/js/home/bootstrap.min.js"></script>
<script src="/js/home/wow.min.js"></script>
<script src="/js/home/main.js"></script>

<script>
new WOW().init();
</script>
<?php  include  VIEW.'layouts'.DIRECTORY_SEPARATOR.'footer.phtml' ?>
