<?php

  include  VIEW.'layouts'.DIRECTORY_SEPARATOR.'header.phtml';
?>
    <!-- start pages photo -->
    <section class="cover-background top-space" style="background-image:url('/images/home/1(1).jpg');">
        <div class="opacity-medium bg-dark"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12 display-table page-title">
                    <div class="vertical-align-middle text-center">
                        <!-- start sub title -->
                        <span class="text-white"></span>
                        <!-- end sub title -->
                        <!-- start page title -->
                        <?php if (array_key_exists('profiles',$this->view_data)){?>
                        <h1 class="text-white"><?php echo Helper::userName(Session::get("userID")) ?></h1>
                        <?php } ?>
                        <!-- end page title -->
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- end pages photo - -->

    <!-- profile page start-->
    <div class="main main-raised">
      <div class="profile-content">
          <div class="container">
              <div class="row">
                <!-- PROFILE PHOTO -->
                <div class="col-md-12 col-xs-12 ml-auto mr-auto profile-div">
                    <div class="profile">
                        <div class="text-center mt-50px">
                          <div class="profile-img-size rounded-circle">
                            <img src="/images/home/user.jpg" alt="Circle Image" class="rounded-circle img-fluid profile-pic" width="auto">
                            <i class="fas fa-user-edit upload-button p-image"></i>
                            <input class="file-upload" type="file" accept="image/*"/>
                          </div>

                        </div>

                        
                        <div>


                      

                          <div class="description">
                              <div class="container">
                              <div class="row">
                                <div class="col-md-12 text-center">
                                  <div class="col-md-12 p-all-20px">
                                  <a href="/editeProfile/edit"><i class="fas fa-edit text-orange"></i></a>

                                    <span class="bio"><?php echo $this->view_data['profiles'][3]['value']; ?></span>
                                    <div class="text-center">
                                      <!-- <span><i class="fas fa-phone text-dark"></i></span> -->
                                      <span><?php echo $this->view_data['profiles'][2]['value']; ?></span>
                                    </div>
                                  </div>
                                 <!-- <a href="/editeProfile/edit" class="btn btn-white"><span style="font-size: 30px">+</span>  Edit My Profile</a> -->
                                </div>




                        
                                </div>
                               
                                  <?php
                                    // if (array_key_exists('profiles',$this->view_data)){
                                    // $html='';
                                    // foreach ($this->view_data['profiles'] as $profile) {
                                     
                                    //     $html.='<div class="p-all-20px"><span class="info-icon" title="'.$profile['name'].'">FN </span>';
                                    //     $html.='</span>  <span class="profile-info-tow">';
                                    //           $html.=$profile['value'];
                                    //         $html.='</span> </div>';
                                            // $html.='<div class="dropdown-divider"></div>';
                                  //   }
                                  // echo $html;
                                  // }
                                  //   ?>
                                </div>
                              </div>
                          </div>
                              <!-- <a href="#pablo" class="btn btn-just-icon btn-link btn-dribbble"><i class="fa fa-dribbble"></i></a>
                              <a href="#pablo" class="btn btn-just-icon btn-link btn-twitter"><i class="fa fa-twitter"></i></a>
                              <a href="#pablo" class="btn btn-just-icon btn-link btn-pinterest"><i class="fa fa-pinterest"></i></a> -->
                        </div>
                    </div>
                </div>
                <!-- PROFILE PHOTO -->

                <!-- TAPS  -->
                <div class="col-md-12 col-xs-12 ml-auto mr-auto prof-tap">
                      <div class="profile-tabs">
                        <ul class="nav nav-pills nav-pills-icons justify-content-center" role="tablist">
                          <li class="nav-item">
                              <a class="nav-link active" href="#works" role="tab" data-toggle="tab" >
                              <?php echo $lang['item102'] ?>
                              </a>
                          </li>
                          <li class="nav-item">
                              <a class="nav-link" href="#favorite" role="tab" data-toggle="tab">
                              <?php echo $lang['item103'] ?>
                              </a>
                          </li>
                        </ul>
                      </div>
                      <div class="tab-content tab-space">
                  <div class="tab-pane active text-center gallery" id="works">
                      <a href="/compaign/addCompaign" class="btn btn-white"><span style="font-size: 30px">+</span> Add Compigan</a>
                      <div class="row" id="user-compign">
                      <?php
                      // print_r($this->view_data);
                       if (array_key_exists('compigan',$this->view_data))
                          foreach ($this->view_data['compigan'] as $row) {
                                      ?>
                          <div class="col-md-4 img-overlay">
                                <div class="card">
                                    <img class="card-img-top" src="/uploads/<?php echo $row['galary'] ?>" alt="Card image cap">
                                    <div class="overlay">
                                    <div class="dropdown">
                                    <span class="dropspan"><i class="fa fa-ellipsis-v"></i></span>
                                    <div class="dropspan-content">
                                    <a href="/manageUserCompaign/index/<?php echo $row['id']; ?>">Edit</a>
                                    <a href="/manageUserCompaign/delete/<?php echo $row['id']; ?>">Delete</a>
                                    </div>
                                    </div>
                                    <div class="text-overlay">
                                      <h5 class="card-title"><?php echo $lang['item102'] ?></h5>
                                      <p class="card-text"><?php echo $row['title'] ?></p>
                                      <a href="/viewCompaign/show/<?php echo $row['id']?>" class="btn btn-home-comp">Go somewhere</a>
                                    </div>
                                    </div>

                                </div>
                                <div class="progress">
                                  <div class="progress-bar progress-bar-style" role="progressbar" style="width: 50%" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100">55%</div>
                                </div>
                         </div>
                                    <?php } ?>
                      </div>
                  </div>
                  <div class="tab-pane text-center gallery" id="favorite">
                          <div class="row">

                              <div class="col-md-12">
                                  <div>
                                    <span class="prof-donate"><i class="fas fa-donate"></i>300$</span>
                                    <a class="text-gray" href="#">Campagin Name</a>
                                  </div>
                                   <div class="dropdown-divider"></div>

                              </div>
                              <div class="col-md-12">
                                  <div>
                                    <span class="prof-donate"><i class="fas fa-donate"></i>300$</span>
                                    <a href="#" class="text-gray">Campagin Name</a>
                                  </div>
                                   <div class="dropdown-divider"></div>


                            <?php
                            $html='';
                            $total=0;
                            if (array_key_exists('donations',$this->view_data))
                             foreach ($this->view_data['donations'] as $row) {
                               $total+=$row["amount"];
                          $html.='<div class="col-md-12  m-2 p-2"> ';
                          $html.='<span class="prof-donate"><i class="fas fa-donate"></i>';
                          $html.=$row["amount"].'</span>';
                          $html.='<a href="/viewCompaign/show/'.$row["compigan_id"].'">'.Helper::getCompaignTitle($row["compigan_id"]).'</a>
                                  <div class="dropdown-divider"></div></div>  ';


                             }
                             echo $html; ?>
                             <div class="col-md-12  m-2 p-2">
                                <strong>Total : </strong>
                               <span class="prof-donate"> <i class="fas fa-donate"></i><?php echo $total; ?></span>
                               <div class="dropdown-divider"></div></div>
                          </div>
                  </div>
                  </div>


                </div>

                <!-- TAPS  -->


          </div></div>
      </div>
  	</div>
	<!-- profile page end -->


<?php  include  VIEW.'layouts'.DIRECTORY_SEPARATOR.'footer.phtml' ?>
