<?php

  include  VIEW.'layouts'.DIRECTORY_SEPARATOR.'header.phtml';
?>
    <!-- start pages photo -->
    <section class="cover-background top-space" style="background-image:url('/images/home/1(1).jpg');">
        <div class="opacity-medium bg-dark"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12 display-table page-title">
                    <div class="vertical-align-middle text-center">
                        <!-- start sub title -->
                        <span class="text-white"><?php echo $lang['item100'] ?></span>
                        <!-- end sub title -->
                        <!-- start page title -->
                        <h1 class="text-white"><?php echo $lang['item101'] ?></h1>
                        <!-- end page title -->
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- end pages photo - -->

    <!-- profile page start-->
    <div class="main main-raised border-50">
      <div class="profile-content">
          <div class="container">
              <div class="row">
                <!-- PROFILE PHOTO -->
                <div class="col-md-4 col-xs-12 ml-auto mr-auto">
                    <div class="profile">
                        <div class="text-center mt-50px circle">
                          <div class="profile-img-size">
                            <img src="/images/home/user.jpg" alt="Circle Image" class="img-raised rounded-circle img-fluid profile-pic" width="auto">
                            <i class="fas fa-user-edit upload-button p-image"></i>
                            <input class="file-upload" type="file" accept="image/*"/>
                          </div>

                        </div>

                        <div class="name">
                          <?php if (array_key_exists('profiles',$this->view_data)){?>
                            <h3 class="title"><?php echo $this->view_data['profiles'][0]['value']; ?></h3>
                          <?php } ?>
                          <div class="description">
                              <div class="container">
                                <div class="row text-center profile-info-all">
                                <a href="/editeProfile" class="btn btn-white"><span style="font-size: 30px">+</span>  Edit My Profile</a>

                                  <?php
                                    if (array_key_exists('profiles',$this->view_data)){
                                    $html='';
                                    foreach ($this->view_data['profiles'] as $profile) {
                                     
                                        $html.='<div class="p-all-20px"><span class="info-icon" title="'.$profile['name'].'">FN </span>';
                                        $html.='</span>  <span class="profile-info-tow">';
                                              $html.=$profile['value'];
                                            $html.='</span> </div>';
                                            // $html.='<div class="dropdown-divider"></div>';
                                    }
                                  echo $html;
                                  }
                                    ?>
                                </div>
                              </div>
                          </div>
                              <!-- <a href="#pablo" class="btn btn-just-icon btn-link btn-dribbble"><i class="fa fa-dribbble"></i></a>
                              <a href="#pablo" class="btn btn-just-icon btn-link btn-twitter"><i class="fa fa-twitter"></i></a>
                              <a href="#pablo" class="btn btn-just-icon btn-link btn-pinterest"><i class="fa fa-pinterest"></i></a> -->
                        </div>
                    </div>
                </div>
                <!-- PROFILE PHOTO -->

                <!-- TAPS  -->
                <div class="col-md-8 col-xs-12 ml-auto mr-auto">
                      <div class="profile-tabs">
                        <ul class="nav nav-pills nav-pills-icons justify-content-center" role="tablist">
                          <li class="nav-item">
                              <a class="nav-link active" href="#works" role="tab" data-toggle="tab" >
                              <?php echo $lang['item102'] ?>
                              </a>
                          </li>
                          <li class="nav-item">
                              <a class="nav-link" href="#favorite" role="tab" data-toggle="tab">
                              <?php echo $lang['item103'] ?>
                              </a>
                          </li>
                        </ul>
                      </div>
                      <div class="tab-content tab-space">
                  <div class="tab-pane active text-center gallery" id="works">
                      <a href="/compaign/addCompaign" class="btn btn-white"><span style="font-size: 30px">+</span> Add Compigan</a>
                      <div class="row" id="user-compign">
                      <?php
                      // print_r($this->view_data);
                       if (array_key_exists('compigan',$this->view_data))
                          foreach ($this->view_data['compigan'] as $row) {
                                      ?>
                          <div class="col-md-6 img-overlay">
                                <div class="card">
                                    <img class="card-img-top" src="/uploads/<?php echo $row['galary'] ?>" alt="Card image cap">
                                    <div class="overlay">
                                    <div class="dropdown">
                                    <span class="dropspan"><i class="fa fa-ellipsis-v"></i></span>
                                    <div class="dropspan-content">
                                    <a href="/manageUserCompaign/index/<?php echo $row['id']; ?>">Edit</a>
                                    <a href="/manageUserCompaign/delete/<?php echo $row['id']; ?>">Delete</a>
                                    </div>
                                    </div>
                                    <div class="text-overlay">
                                      <h5 class="card-title"><?php echo $lang['item102'] ?></h5>
                                      <p class="card-text"><?php echo $row['title'] ?></p>
                                      <a href="/viewCompaign/show/<?php echo $row['id']?>" class="btn btn-home-comp">Go somewhere</a>
                                    </div>
                                    </div>
                                </div>
                                <div class="progress">
                                  <div class="progress-bar" role="progressbar" style="width: 50%" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100">55%</div>
                                </div>
                         </div>
                                    <?php } ?>
                      </div>
                  </div>
                  <div class="tab-pane text-center gallery" id="favorite">
                          <div class="row">
                              <div class="col-md-3">
                                  <!-- <div class="card" style="width: 18rem;">
                                      <img class="card-img-top" src="..." alt="Card image cap">
                                      <div class="card-body">
                                        <h5 class="card-title">Card title</h5>
                                        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                                        <a href="#" class="btn btn-primary">Go somewhere</a>
                                      </div>
                                    </div> -->
                              </div>
                          </div>
                  </div>
                  </div>

                </div>
                </div>

                <!-- TAPS  -->


          </div>
      </div>
  	</div>
	<!-- profile page end -->


<?php  include  VIEW.'layouts'.DIRECTORY_SEPARATOR.'footer.phtml' ?>
