<?php

  include  VIEW.'layouts'.DIRECTORY_SEPARATOR.'head.phtml'; ?>
   <!-- start Sign Up -->
<body class="bg-blue">

   <section>
			<div class="container register">
					<div class="row">
						<div class="col-md-12 register-left">
							<a href="/home/index">
								<img src="/images/home/logo.png" alt=""/>
							</a>

							<h3>Welcome</h3>
							<p class="p-login nots-p-reg">You have already account! <a href="/auth/login">LogIn</a></p>

						</div>
						<div class="col-md-12 register-right shadow-div">

							<div class="tab-content" id="myTabContent">
								<div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
									<h3 class="register-heading"> Sing Up</h3>
									<form class="" action="" method="post" name='signupForm' id="signupForm">
									<div class="row register-form wow flipInX">
									<div class="col-md-6">
											<div class="form-group">
												<label for="first_name" class="laple-forms">First Name</label>
												<input type="text" class="form-control" placeholder="First Name *"  name="first_name" value="" oninput=" stringlength(document.signupForm.first_name,5,12); allLetter(document.signupForm.first_name);preventSpace(document.signupForm.first_name,0,0)" />
						  <?php echo Message::check('first_name');  ?>
						  <span class="text-danger text-error" id="first_nameError"> </span>
						  						<span id="first_nameError"></span>
											</div>
											<div class="form-group">
												<label for="last_name" class="laple-forms">Last Name</label>
												<input type="text" class="form-control" placeholder="Last Name *" name="last_name" value="" oninput=" stringlength(document.signupForm.last_name,5,12); allLetter(document.signupForm.last_name);preventSpace(document.signupForm.first_name,0,0)" />
						  <?php echo Message::check('last_name');  ?>
						  <span class="text-danger text-error" id="last_nameError"> </span>
											</div>
											<div class="form-group">
												<label for="email" class="laple-forms">Your Email</label>
												<input type="email" name="email" class="form-control" placeholder="Your Email *" value="" oninput=" ValidateEmail(document.signupForm.email);" />
						  <?php echo Message::check('email');  ?>
						  <span class="text-danger text-error" id="emailError"> </span>

											</div>
											</div>		
											<div class="col-md-6">
											<div class="form-group">
												<label for="password" class="laple-forms">Your Password</label>
												<input type="password" class="form-control" placeholder="Password *" name="password" value=""  oninput="stringlength(document.signupForm.password,8,15);" />
						  <?php echo Message::check('password');  ?>
						  <span class="text-danger text-error" id="passwordError"> </span>

											</div>
											<div class="form-group">
												<label for="confirm_password" class="laple-forms">Confirm Password</label>
												<input type="password" class="form-control" name="confirm_password"  placeholder="Confirm Password *" value="" oninput=" confirmPassValidation(document.signupForm.confirm_password,document.signupForm.password)"; />
							<?php echo Message::check('confirm_password');  ?>
							<span class="text-danger text-error" id="confirm_passwordError"> </span>

												</div>
										
											<div class="form-group">
												<label for="phone" class="laple-forms">Your Phone</label>
												<input type="text" minlength="10" maxlength="10" name="phone" class="form-control" placeholder="Your Phone *" value="" oninput="phonenumber(document.signupForm.phone)"; />
						  <?php echo Message::check('phone');  ?>
						  <span class="text-danger text-error" id="phoneError"> </span>

											</div>
											<center>
											<input id="signuptBtn" type="submit" class="btnRegister float-none"  value="Sing Up"/>
											
											</center>

											</div>
										

										
											<!-- <p class="p-login">You have already account! <a href="login.html">LogIn</a></p> -->
										
										
									</div>
								</div>
</form>

							</div>
						</div>
					</div>

				</div>
	</section>
	
    <!-- end Sign Up -->
	<script>
$(document).ready(function(){
    $("#signuptBtn").click(function(){  
		event.preventDefault();  
		if(Requirevalidation(document.signupForm.first_name)&&Requirevalidation(document.signupForm.last_name)&&
		Requirevalidation(document.signupForm.email)&&Requirevalidation(document.signupForm.password)&&
		Requirevalidation(document.signupForm.confirm_password)&&Requirevalidation(document.signupForm.phone))    
        $("#signupForm").submit(); // Submit the form
    });
});
</script>
<?php  include  VIEW.'layouts'.DIRECTORY_SEPARATOR.'footer.phtml' ?>
