
<?php include  VIEW.'layouts'.DIRECTORY_SEPARATOR.'head.phtml';?>
<body class="bg-blue">
<div class="container welcome-form">
    <div class="row">
        <div class="col-md-12 register-left">
                <div class="animation-ttp">
                <a href="/home/index">
                    <img src="/images/home/logo.png" alt=""/>
                </a>
                </div>
                <div class="p-5">
                <h1><?php echo $lang['item92']?> <span class="text-yellow"> <?php  echo Session::get('userName');?></span>!</h1>
                <p><?php echo $lang['item93']?></p>
                <h3><?php echo $lang['item94']?></h3>
                <p class="p-login nots-p-reg"><?php echo $lang['item95']?> <a href="/home/index"><?php echo $lang['item96']?>!</a></p>

                </div>
            
        </div>
    </div>
</div>
   
       <script>
         setTimeout(function(){
            window.location.href = '/home/index';
         }, 190000000);
      </script>
      
<?php  include  VIEW.'layouts'.DIRECTORY_SEPARATOR.'footer.phtml' ?>

