<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>Welcome 2 found me</h1>
    <p>Agreat Cooperative society</p>
    <h3>we will redirect you now </h3>
    <script>
         setTimeout(function(){
            window.location.href = 'http://localhost:8008/home/index';
         }, 2000);
      </script>
</body>

</html>