<?php include  VIEW.'layouts'.DIRECTORY_SEPARATOR.'head.phtml';?>
<body class="bg-blue">
<div class="container welcome-form">
    <div class="row">
        <div class="col-md-12 register-left">
                <div class="animation-ttp">
                <a href="/home/index">
                    <img src="/images/home/logo.png" alt=""/>
                </a>
                </div>
                <div class="p-5">
                <h1>WELCOME <span class="text-yellow"> <?php  echo Session::get('userName');?></span>!</h1>
                <p>Agreat Cooperative society</p>
                <h3>we will redirect you now </h3>
                <p class="p-login nots-p-reg">If not <a href="/auth/signup">Click Here!</a></p>

                </div>
            
        </div>
    </div>
</div>
   
       <script>
         setTimeout(function(){
            window.location.href = '/home/index';
         }, 2000);
      </script>
      
<?php  include  VIEW.'layouts'.DIRECTORY_SEPARATOR.'footer.phtml' ?>

