<ul class="navbar-nav sidebar sidebar-light accordion" id="accordionSidebar">
      <a class="d-flex align-items-center justify-content-center" href="">
        <div class="sidebar-brand-icon">
          <img src="/images/logo.png" style="width: 50px; height: 50px; margin-top: 8px; margin-left: -7px;" alt="">
        </div>

      </a>

      <li class="nav-item ">
        <a  class=" nav-link" href="/cp/index.phtml">
          <i class="fa fa-sticky-note"></i>
          <span>Pages</span><span class="badge float-right" style="background:green;color:#fff;">15</span></a>
          
      </li>
      
      <li class="nav-item ">
        <a  class=" nav-link" href="index.php">
          <i class="fa fa-outdent"></i>
          <span >Compign</span><span class="badge float-right" style="background:brown;color:#fff;">300</span></a>
      </li>
      <li class="nav-item ">
        <a  class=" nav-link" href="index.php">
          <i class="fa fa-comments"></i>
          <span>Comments</span><span class="badge float-right" style="background:gray;color:#fff;">3400</span></a>
      </li>
      <li class="nav-item ">
      <div class="panel panel-default">

        <a  class=" nav-link" data-toggle="collapse" href="#collapse1">

          <i class="fa fa-users"></i>
          <span>Users</span><span class="badge float-right" style="background:orange;color:#fff;">25</span></a>
          <div id="collapse1" class="panel-collapse collapse">
      <div class="panel-body"><a class=" nav-link " href="/manageusers/ShowDeletedUsers">Active Users</a> </div>
      <div class="panel-body"><a class=" nav-link " href="/manageusers/showActiveUsers">Deleted Users</a> </div>
    </div>
  </div>
      </li>
      <li class="nav-item ">
        <a  class=" nav-link " href="index.php">
          <i class="fa fa-wrench"></i>
          <span>Settings</span></a>
      </li>   
    </ul>

