<ul class="navbar-nav sidebar sidebar-light accordion" id="accordionSidebar">
      <a class="d-flex align-items-center justify-content-center" href="/home/index">
        <div class="sidebar-brand-icon">
          <img src="/images/logo.png" style="width: 60px; height: 60px; margin-top: 8px; margin-left: -7px;" alt="">
        </div>

      </a>
      <li class="nav-item">
        <a  class="nav-link font-size-18px" href="/admin/index">
          <i class="fa fa-dashboar"></i>

          <span>Pages</span>
          <!-- <span class="badge float-right" style="background:green;color:#fff;">15</span> -->
        </a>

      </li>


      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsCompaign"
          aria-expanded="true" aria-controls="collapsCompaign">
          <i class="far fa-fw fa-window-maximize"></i>
          <span>Compaigns</span>
        </a>
        <div id="collapsCompaign" class="collapse" aria-labelledby="headingBootstrap" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Compaigns managment</h6>
            <a class="collapse-item" href="/managecompaign/ShowPindingUpdateCompaigns">Pending Update Compaigns</a>
            <a class="collapse-item" href="/managecompaign/ShowPindingDeleteCompaigns">Pending Delete Compaigns</a>
            <a class="collapse-item" href="/managecompaign/ShowPindingCompaigns">Pending Compaigns</a>
            <a class="collapse-item" href="/managecompaign/ShowActiveCompaigns">Active Compaigns</a>
            <a class="collapse-item" href="/managecompaign/ShowPausedCompaigns">Paused Compaigns</a>
            <a class="collapse-item" href="/managecompaign/ShowDeletedCompaigns">Deleted Compaigns</a>
          </div>
        </div>
      </li>

      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsComments"
          aria-expanded="true" aria-controls="collapsComments">
          <i class="fa fa-comments"></i>
          <span>Comments</span>
        </a>
        <div id="collapsComments" class="collapse" aria-labelledby="headingBootstrap" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Comments managment</h6>
            <a class="collapse-item" href="/managecomment/showActiveComments">Active Comments</a>
            <a class="collapse-item" href="/managecomment/showDeletedComments">Deleted Comments</a>
          </div>
        </div>
      </li>

      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsUsers"
          aria-expanded="true" aria-controls="collapsUsers">
          <i class="fa fa-users "></i>
          <span>Users</span>
        </a>
        <div id="collapsUsers" class="collapse" aria-labelledby="headingBootstrap" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">User managment</h6>
            <a class="collapse-item" href="/manageusers/showPendingUsers">Pending Users</a>
            <a class="collapse-item" href="/manageusers/showActiveUsers">Active Users</a>
            <a class="collapse-item" href="/manageusers/ShowDeletedUsers">Deleted Users</a>
          </div>
        </div>
      </li>



      <li class="nav-item ">
        <a  class=" nav-link " href="index.php">
          <i class="fa fa-wrench"></i>
          <span>Settings</span></a>
      </li>
    </ul>
