<script src="/layout/js/jquery-3.4.1.min.js"></script>
    <script src="/layout/js/popper.min.js"></script>
    <script src="/layout/js/bootstrap.min.js"></script>
    <script src="/layout/js/jquery-ui.min.js"></script>
    <script src="/layout/js/iconify.min.js"></script>
    <script src="/layout/assets/js/plugins/chart.js/dist/Chart.min.js"></script>
    <script src="/layout/assets/js/plugins/chart.js/dist/Chart.extension.js"></script>
    <script src="/layout/assets/js/argon-dashboard.min.js?v=1.1.0"></script>
    <script src="https://unpkg.com/bootstrap-table@1.15.5/dist/bootstrap-table.min.js"></script>
    <script src="/layout/js/main.js"></script>
    <script src="/layout/js/new.js"></script>
    

 
    
  


errMsg(<?php echo'"'.Message::check('main').'"'; ?>);


</body>
</html>
