
<div id="content-wrapper" class="d-flex flex-column">
      <div id="content">
        <!-- TopBar -->
        <nav class="navbar navbar-expand topbar mb-4 static-top" style="background-color: #fff; border-left:1px solid #f1f1f1;">
          <button id="sidebarToggleTop" class="btn btn-link rounded-circle mr-3" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" >
            <i class="fa fa-bars small-icon text-blue"></i>
          </button>

          <ul class="navbar-nav " style="position: absolute;right:20px;">

      <li class="nav-item dropdown clnav-n">
                  <a class="nav-link dropdown-toggle notification" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fa fa-bell font-size-20px"></i>
                    <span class="badge wow pulse">3</span>
                  </a>
                    <ul class="dropdown-menu" style="margin-right: 30px;">
                      <li class="head text-light">
                        <div class="row">
                          <div class="col-lg-12 col-sm-12 col-12">
                            <!-- <span>Notifications (3)</span> -->
                            <!-- <a href="" class="float-right text-light">Mark all as read</a> -->
                          </div>
                      </li>
                      <div id="noti-body">

                      </div>
                      <li class="footer text-center">
                        <a href="" class="text-blue">View All</a>
                      </li>
                    </ul>
                </li>
      	<li class="nav-item dropdown clnav">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
         <i class="fa fa-user font-size-20px"></i>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="/auth/logout">Logout</a>

      </li>

          </ul>
        </nav>
        <!-- Topbar -->

         <!-- notification -->
         <li class="nav-item dropdown">
                            <a class="nav-link text-light" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                              <i class="fa fa-bell"></i>
                            </a>
                              <ul class="dropdown-menu">
                                <li class="head text-light bg-dark">
                                  <div class="row">
                                    <div class="col-lg-12 col-sm-12 col-12">
                                      <span>Notifications (3)</span>
                                      <a href="" class="float-right text-light">Mark all as read</a>
                                    </div>
                                </li>
                                <li class="notification-box">
                                  <div class="row">
                                    <div class="col-lg-3 col-sm-3 col-3 text-center">
                                      <img src="/demo/man-profile.jpg" class="w-50 rounded-circle">
                                    </div>
                                    <div class="col-lg-8 col-sm-8 col-8">
                                      <strong class="text-info">David John</strong>
                                      <div>
                                        Lorem ipsum dolor sit amet, consectetur
                                      </div>
                                      <small class="text-warning">27.11.2015, 15:00</small>
                                    </div>
                                  </div>
                                </li>
                                <li class="notification-box bg-gray">
                                  <div class="row">
                                    <div class="col-lg-3 col-sm-3 col-3 text-center">
                                      <img src="/demo/man-profile.jpg" class="w-50 rounded-circle">
                                    </div>
                                    <div class="col-lg-8 col-sm-8 col-8">
                                      <strong class="text-info">David John</strong>
                                      <div>
                                        Lorem ipsum dolor sit amet, consectetur
                                      </div>
                                      <small class="text-warning">27.11.2015, 15:00</small>
                                    </div>
                                  </div>
                                </li>
                                <li class="notification-box">
                                  <div class="row">
                                    <div class="col-lg-3 col-sm-3 col-3 text-center">
                                      <img src="/demo/man-profile.jpg" class="w-50 rounded-circle">
                                    </div>
                                    <div class="col-lg-8 col-sm-8 col-8">
                                      <strong class="text-info">David John</strong>
                                      <div>
                                        Lorem ipsum dolor sit amet, consectetur
                                      </div>
                                      <small class="text-warning">27.11.2015, 15:00</small>
                                    </div>
                                  </div>
                                </li>
                                <li class="footer bg-dark text-center">
                                  <a href="" class="text-light">View All</a>
                                </li>
                              </ul>
                          </li>
