

<div id="content-wrapper" class="d-flex flex-column">
      <div id="content">
        <!-- TopBar -->
        <nav class="navbar navbar-expand topbar mb-4 static-top" style="background-color: #fff; border-left:1px solid #f1f1f1;">
          <button id="sidebarToggleTop" class="btn btn-link rounded-circle mr-3" id="navbarDropdown" role="button" data-toggle="headingBootstrap" aria-haspopup="true" aria-expanded="false" >
            <i class="fa fa-bars small-icon text-blue"></i>

          </button>

          <ul class="navbar-nav " style="position: absolute;right:20px;">


      <li class="nav-item dropdown clnav-n">
                  <a class="nav-link dropdown dropdown-toggle notification" href="#"   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fa fa-bell font-size-20px"></i>
                    <span class="badge wow pulse noti-count"></span>
                  </a>
                  <ul class="dropdown-menu " aria-labelledby="dropdown">
                                <li class="head text-light bg-light">
                                  <div class="row">
                                    <div class="col-lg-12 col-sm-12 col-12">
                                      <span class="noti-header"> Last Notification</span>
                                    </div>
                                </li>



                                <div id="noti-body">

                                </div>


                   </ul>
                </li>
      	<li class="nav-item dropdown clnav">
        <a class="nav-link " href="/auth/logout" id="navbarDropdownMenuLink" role="button" >


         <i class="fas fa-sign-out-alt font-size-20px"><i>  </i></i>


        </a>



      </li>

          </ul>
        </nav>
        <nav>


</nav>
        <!-- Topbar -->

         <!-- notification -->
<!-- hide menu -->
<div class="container-fluid" id="container-wrapper">
         <div class="d-sm-flex cphead align-items-center justify-content-between mb-4">
           <ol class="breadcrumb">

             <li class="breadcrumb-item"><a href="/admin/index"><?php echo $this->getController(); ?></a></li>
             <li class="breadcrumb-item  " aria-current="page"><?php echo $this->getActionِِ(); ?></li>
           </ol>

         </div>
<!-- end hide menu -->
