
<?php
require_once   VIEW.'cp_layouts'.DIRECTORY_SEPARATOR.'header.phtml';
require_once  VIEW.'cp_layouts'.DIRECTORY_SEPARATOR.'fixedBar.phtml';
require_once  VIEW.'cp_layouts'.DIRECTORY_SEPARATOR.'navBar.phtml';

?>
 <div class="container-fluid" id="container-wrapper">
          <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800"></h1>
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="./">analytics</a></li>
              <li class="breadcrumb-item active" aria-current="page">Dashboard</li>
            </ol>
          </div>
          <div class="panel panel-default">


<div class="panel-body home-stats text-center">


  <div class="col-md-3  pg-color-blue stat">

    <div class="title-db">Total Users</div>
    <span class="fa fa-users"></span>
    <span class="f-28px"><?php echo $this->view_data['users'];?></span>
</div>
<div class="col-md-3 pg-color-green stat">

    <div class="title-db">Total Compains</div>
    <span class="fas fa-wallet"></span>
    <span class="f-28px"><?php echo $this->view_data['compaigns'];?></span>
</div>
<div class="col-md-3 pg-color-yellow stat">

    <div class="title-db">Total Comments</div>
    <span class="fas fa-comment"></span>
    <span class="f-28px"><?php echo $this->view_data['comments'];?></span>
</div>
<div class="col-md-3  pg-color-pink stat">

    <div class="title-db">Total Visits</div>
    <span class="fas fa-inbox"></span>
    <span class="f-28px"><?php echo $this->view_data['visits'];?></span>
</div>


</div>



<div class="panel-body home-stats text-center">


  <div class="col-md-3  pg-color-blue stat">

    <div class="title-db">Total Donars</div>
    <span class="	fas fa-donate"></span>
    <span class="f-28px"><?php echo $this->view_data['donarsCount'];?></span>
</div>
<div class="col-md-3 pg-color-green stat">

    <div class="title-db">Amount of Donars</div>
    <span class="fas fa-dollar-sign"></span>
    <span class="f-28px"><?php echo $this->view_data['donarsSum'];?></span>
</div>
<div class="col-md-3 pg-color-yellow stat">

    <div class="title-db">Total Comments</div>
    <span class="fa fa-comments"></span>
    <span class="f-28px">20</span>
</div>
<div class="col-md-3  pg-color-pink stat">

    <div class="title-db">Total Money</div>
    <span class="fa fa-home"></span>
    <span class="f-28px">15</span>
</div>


</div>


</div>

<table class="table table-striped mt-3">

</table>

</div>


</div>
</div>
<?php
require_once VIEW.'cp_layouts'.DIRECTORY_SEPARATOR.'footer.phtml';
?>
