
<?php
require_once   VIEW.'cp_layouts'.DIRECTORY_SEPARATOR.'header.phtml';
require_once  VIEW.'cp_layouts'.DIRECTORY_SEPARATOR.'fixedBar.phtml';
require_once  VIEW.'cp_layouts'.DIRECTORY_SEPARATOR.'navBar.phtml';
?>
 <div class="container-fluid" id="container-wrapper">
          <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Dashboard</h1>
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="./">Home</a></li>
              <li class="breadcrumb-item active" aria-current="page">Dashboard</li>
            </ol>
          </div>
          <div class="panel panel-default">


<div class="panel-body home-stats text-center">


  <div class="col-md-3  stat" style="background:#48587d;width:150px; color:#fff">

    <div>Total Users</div>
    <span class="fa fa-users "  style="font-size:25px;"></span>
    <span>220</span>
</div>
<div class="col-md-3  stat" style="background:#614847; width:150px; color:#fff">

    <div>Total Compains</div>
    <span class="fa fa-outdent "  style="font-size:25px;"></span>
    <span>12</span>
</div>
<div class="col-md-3 stat" style="background:#7bc77e;width:150px;color:#fff">

    <div>Total Comments</div>
    <span class="fa fa-comments " style="font-size:25px;"></span>
    <span>20</span>
</div>
<div class="col-md-3  stat" style="background:#698079;width:150px;color:#fff;">

    <div>Total Money</div>
    <span class="fa fa-home"  style="font-size:25px;"></span>
    <span>15</span>
</div>


</div>



</div>

<table class="table table-striped mt-3">
<thead  class="mt-5 bg-dark"style="background:#eee;color:#fff">
<tr>
  <th scope="col">#</th>
  <th scope="col">First</th>
  <th scope="col">Last</th>
  <th scope="col">Handle</th>
    </tr>
</thead>
<tbody>
  <tr>
  <th scope="row">1</th>
  <td>Mark</td>
  <td>Otto</td>
  <td>@mdo</td>
</tr>
<tr>
  <th scope="row">2</th>
  <td>Jacob</td>
  <td>Thornton</td>
  <td>@fat</td>
</tr>
  <tr>
  <th scope="row">3</th>
  <td>Larry</td>
  <td>the Bird</td>
  <td>@twitter</td>
</tr>
<tr>
  <th scope="row">4</th>
  <td>Larry</td>
  <td>the Bird</td>
  <td>@twitter</td>
</tr>
<tr>
  <th scope="row">5</th>
  <td>Larry</td>
  <td>the Bird</td>
  <td>@twitter</td>
</tr>
</tbody>
</table>
<div class="alert alert-success" role="alert">
<h4 class="alert-heading">Well done!</h4>
<p>Aww yeah, you successfully read this important alert message. This example text is going to run a bit longer so that you can see how spacing within an alert works with this kind of content.</p>
<hr>
<p class="mb-0">Whenever you need to, be sure to use margin utilities to keep things nice and tidy.</p>
</div>
</div>


</div>
</div>
<?php
require_once VIEW.'cp_layouts'.DIRECTORY_SEPARATOR.'footer.phtml';
?>
