
<?php
require_once   VIEW.'cp_layouts'.DIRECTORY_SEPARATOR.'header.phtml';
require_once  VIEW.'cp_layouts'.DIRECTORY_SEPARATOR.'fixedBar.phtml';
require_once  VIEW.'cp_layouts'.DIRECTORY_SEPARATOR.'navBar.phtml';
?>




  <div class="user" style="background-color: #fff; padding:50px;border-radius: 40px; " >
  

  <div id="toolbar">
    <button id="remove" class="btn btn-danger" disabled>
      <i class="glyphicon glyphicon-remove"></i> Pinding Compaign
    </button>
  </div>
  <table
  id="table"
  data-toolbar="#toolbar"
  data-search="true"
  data-show-toggle="true"
  data-show-fullscreen="true"
  data-show-columns="true"
  data-show-columns-toggle-all="true"
  data-detail-view="true"
  data-show-export="true"
  data-click-to-select="true"
  data-detail-formatter="detailFormatter"
  data-minimum-count-columns="2"
  data-show-pagination-switch="true"
  data-pagination="true"
  data-id-field="id"
  data-page-list="[10, 25, 50, 100, all]"

  >
  </table>
</div>



<!-- model  -->

<div id="changeCompaigns" class="modal fade">
		<div class="modal-dialog">
			<div class="modal-content">
				<form>

					<div class="modal-header">
						<h4 class="modal-title "> Change compaign status</h4>
						<button type="button" class="close mr-5" data-dismiss="modal" aria-hidden="true">×</button>
					</div>
					<div class="modal-body">
						<input type="hidden" id="id_d" name="id" class="form-control">
						<input type="hidden" id="state_d" name="state" class="form-control">
						<p>Are you sure to continue this process?</p>

					</div>
					<div class="modal-footer">
					<input type="button" class="btn btn-info" id="delete" onclick="deleteU()" value="Confirm">
						<button type="button" class="btn btn-danger"  data-dismiss="modal">cancel</button>
					</div>
				</form>
			</div>
		</div>
  </div>
<!-- model -->


<!-- model  -->

<div id="viewCompaigns" class="modal fade">
		<div class="modal-dialog modal-l">
			<div class="modal-content">
        <!-- Modal Header -->
      <div class="modal-header bg-dark text-light">
        <h4 class="modal-title" id="compaignTitle"></h4>
        <button type="button" class="close text-light" data-dismiss="modal">&times;</button>
      </div>

              <div class="modal-body">


                  <img class="card-img-top h-25" src="" alt="Card image cap" id="galary">
                  <div class="card-body">

                    <h5 class="card-title"></h5>

                    <p class="card-text" id="descrption">...</p>
                    <input type="hidden" name="" value="" id="compaignID">
                  <ul class="list-group list-group-flush text-muted">

                   <li class="list-group-item" id="IDcompaign"></li>
                    <li class="list-group-item" id="duration"></li>
                    <li class="list-group-item" id="cost"></li>

          <li class="list-group-item">  <a href="" class="card-link" target="_blank" id="file">PDF File link</a></li>



                  </ul>
                  </div>


                  </div>
      <!-- Modal footer -->
      <div class="modal-footer">
        <a class="reject btn btn-warning" href="javascript:void(0)" title="Reject">
          Reject
        <i class="fa fa-trash"></i>
        </a>
        <a class="add btn btn-primary" href="javascript:void(0)" title="Approve">
          Approve
        <i class="fa fa-check-square "></i>
        </a>
       </div>
      </div>
			</div>
		</div>

<!-- model -->


  <script>
    var $table = $('#table')
    var $remove = $('#remove')
    var selections = []

    function getIdSelections() {
      return $.map($table.bootstrapTable('getSelections'), function (row) {
        return row.id
      })
    }

    function responseHandler(res) {
      $.each(res.rows, function (i, row) {
        row.state = $.inArray(row.id, selections) !== -1
      })
      return res
    }

    function detailFormatter(index, row) {
      var html = []
      $.each(row, function (key, value) {
        html.push('<p><b>' + key + ':</b> ' + value + '</p>')
      })
      return html.join('')
    }

    function operateFormatter(value, row, index) {
      return [

        '<a class="view" href="javascript:void(0)" title="Approve">',
        '<i class="fa fa-eye "></i>',
        '</a>'
      ].join('')
    }


  // delete fun
  function deleteU(){
    $.ajax({
      url: "/managecompaign",
        type: "POST",
        cache: false,
        data:{
            type:4,
            ids: $("#id_d").val(),
            state:$("#state_d").val(),

        },
        success: function(dataResult){
            var dataResult = JSON.parse(dataResult);
            if(dataResult.statusCode==200){
                $('#changeCompaigns').modal('hide');
                errMsg(dataResult.message);
                // sucMsg(dataResult.message);
                load_data()
            }
            else if(dataResult.statusCode==201){
               errMsg(dataResult);
            }
    }
    });
}



    window.operateEvents = {
      'click .view': function (e, value, row, index) {


        $('#compaignTitle').text(row.title);
          $('#descrption').html(row.descrption);
          $('#duration').text(row.duration);

          $('#IDcompaign').text(" ID : "+row.id);
          $('#compaignID').val(row.id);
          $('#cost').text(row.cost+" $");
          $('#file').attr('href','/uploads/'+row.file)
        $.ajax({
          url:"/uploads/"+row.galary+"",
          xhrFields:{
            responseType:'blob'
          },
          success:function(data)
          {
            var img=document.getElementById('galary');
            var url=window.URL || window.webkitURL;
            img.src=url.createObjectURL(data);
          }


               });

        $('#viewCompaigns').modal('show');

      },

      'click .like': function (e, value, row, index) {
        alert('You click like action, row: ' + JSON.stringify(row))
      },
      'click .add': function (e, value, row, index) {

        // alert (row.id)

    $('#id_d').val(row.id);
    $('#state_d').val(2);
    $('#changeCompaigns').modal('show');},
    'click .reject': function (e, value, row, index) {
      // alert (row.id)

  $('#id_d').val(row.id);
  $('#state_d').val(0);
  $('#changeCompaigns').modal('show');

  }



}


$(".add").click(function(){
  var Id=$('#compaignID').val();
  $('#id_d').val(Id);
  $('#state_d').val(2);
  $('#viewCompaigns').modal('hide');
  $('#changeCompaigns').modal('show');
});

$(".reject").click(function(){
  var Id=$('#compaignID').val();
  $('#id_d').val(Id);
  $('#state_d').val(0);
  $('#viewCompaigns').modal('hide');
  $('#changeCompaigns').modal('show');
});

        // $table.bootstrapTable('remove', {
        //   field: 'id',
        //   values: [row.id]


    function totalTextFormatter(data) {
      return 'Total'
    }

    function totalNameFormatter(data) {
      return data.length
    }

    function totalPriceFormatter(data) {
      var field = this.field
      return '$' + data.map(function (row) {
        return +row[field].substring(1)
      }).reduce(function (sum, i) {
        return sum + i
      }, 0)
    }

    function initTable(users) {
      $table.bootstrapTable('destroy').bootstrapTable({
        height: 550,
        locale: $('#locale').val(),
        pagination: true,
        search: true,
        columns: [
          [{
            field: 'state',
            checkbox: true,
            rowspan: 2,
            align: 'center',
            valign: 'middle'
          }, {
            title: ' ID',
            field: 'id',
            rowspan: 2,
            align: 'center',
            valign: 'middle',
            sortable: true,
            footerFormatter: totalTextFormatter
          }, {
            title: 'Compaigns Details',
            colspan: 5,
            align: 'center'
          }],
          [ {
            field: 'title',
            title: 'Compain Title',
            sortable: true,
            align: 'center',
            footerFormatter: totalPriceFormatter
          }, {
            field: 'tags',
            title: 'Tags',
            sortable: true,
            align: 'center',
            footerFormatter: totalPriceFormatter
          }
          ,{
            field: 'cost',
            title: 'Cost',
            sortable: true,
            align: 'center',
            footerFormatter: totalPriceFormatter
          }
          ,
          {
            field: 'created_at',
            title: 'Date Created',
            sortable: true,
            align: 'center',
            footerFormatter: totalPriceFormatter
          }
          , {
            field: 'operate',
            title: 'Item Action',
            align: 'center',
            clickToSelect: false,
            events: window.operateEvents,
            formatter: operateFormatter
          }]
        ],
        data:users

      })
    }
      $table.on('check.bs.table uncheck.bs.table ' +
        'check-all.bs.table uncheck-all.bs.table',
      function () {
        $remove.prop('disabled', !$table.bootstrapTable('getSelections').length)

        // save your data, here just save the current page
        selections = getIdSelections()
        // push or splice the selections if you want to save all data selections
      })
      $table.on('all.bs.table', function (e, name, args) {
        console.log(name, args)
      })
      $remove.click(function () {
        var ids = getIdSelections()
        $('#id_d').val( ids);
    $('#changeCompaigns').modal('show');


      })


    // $(function() {
    //   initTable()

    //   $('#locale').change(initTable)
    // })


 $(document).ready(function(){
      	load_data();
  });


 function load_data(){
		$.ajax({
			url:"/managecompaign",
			method:"POST",
      data:{type:"1"},
			success:function(data)
			{
        var userInfo=JSON.parse(data);
        // alert(d)
        initTable(userInfo.data);
        $('#locale').change(initTable)
      }


		       });
}



  </script>

</body>
</html>

<?php
require_once VIEW.'cp_layouts'.DIRECTORY_SEPARATOR.'footer.phtml';
?>
