<!-- footer start -->
<footer class="footer text-center ">
	<p><a href="home.html" target="_blank">&copy; 2020 foundme.com</a></p>
</footer>
	<!-- footer end -->
<script src="/js/home/js.js"></script>
<script src="/js/home/popper.min.js"></script>
<script src="/js/home/bootstrap.min.js"></script>
<script src="/js/home/wow.min.js"></script>
<script src="/js/home/main.js"></script>
<script src="/js/home/jquery.toast.js"></script>


	<script>
	new WOW().init();
	
	function errMsg($msg){
    $.toast({
        text: $msg, // Text that is to be shown in the toast
        heading: 'Note', // Optional heading to be shown on the toast
        icon: 'info', // Type of toast icon
        showHideTransition: 'fade', // fade, slide or plain
        allowToastClose: true, // Boolean value true or false
        hideAfter: 5000, // false to make it sticky or number representing the miliseconds as time after which toast needs to be hidden
        stack: 5, // false if there should be only one toast at a time or a number representing the maximum number of toasts to be shown at a time
        position: 'bottom-right', // bottom-left or bottom-right or bottom-center or top-left or top-right or top-center or mid-center or an object representing the left, right, top, bottom values
        
        
        
        textAlign: 'left',  // Text alignment i.e. left, right or center
        loader: true,  // Whether to show loader or not. True by default
        loaderBg: '#ffffff',  // Background color of the toast loader
        beforeShow: function () {}, // will be triggered before the toast is shown
        afterShown: function () {}, // will be triggered after the toat has been shown
        beforeHide: function () {}, // will be triggered before the toast gets hidden
        afterHidden: function () {}  // will be triggered after the toast has been hidden
    });
}
	</script>

<?php echo Message::check('main'); ?>
</body>
</html>