<script src="/js/home/js.js"></script>
<script src="/js/home/wow.min.js"></script>
<script src="/js/home/main.js"></script>
<script src="/js/home/jquery.toast.js"></script>
<script type="text/javascript">
var jQuery_toast = $.noConflict(true);
</script>

<script type="text/javascript">
$(".file-upload").on('change',function(){

$(".from-upload").submit();
});
</script>
<script>
	new WOW().init();

	function errMsg(msg){
        if(msg!=''){
    jQuery_toast.toast({
        text: msg, // Text that is to be shown in the toast
        heading: 'Note', // Optional heading to be shown on the toast
        icon: 'info', // Type of toast icon
        showHideTransition: 'fade', // fade, slide or plain
        allowToastClose: true, // Boolean value true or false
        hideAfter: 6000, // false to make it sticky or number representing the miliseconds as time after which toast needs to be hidden
        stack: 5, // false if there should be only one toast at a time or a number representing the maximum number of toasts to be shown at a time
        position: 'bottom-right', // bottom-left or bottom-right or bottom-center or top-left or top-right or top-center or mid-center or an object representing the left, right, top, bottom values



        textAlign: 'left',  // Text alignment i.e. left, right or center
        loader: true,  // Whether to show loader or not. True by default
        loaderBg: '#ffffff',  // Background color of the toast loader
        beforeShow: function () {}, // will be triggered before the toast is shown
        afterShown: function () {}, // will be triggered after the toat has been shown
        beforeHide: function () {}, // will be triggered before the toast gets hidden
        afterHidden: function () {}  // will be triggered after the toast has been hidden
    });
        }
}

errMsg(<?php echo'"'.Message::check('main').'"'; ?>);



function converLanguage(lang,dir){

jQuery_1_3_2.ajax({
     url:"/language",
     method:"POST",
     data:{method:"convertLang",lang:lang,dir:dir},
     success:function(data)
     {
      var result=JSON.parse(data);

       if(result.statusCode==200){
          setTimeout(function(){
              location. reload();
          }, 2000);
      }

     }
});

}
//////////////////////////////////validation.js
function stringlength(inputText, minlength, maxlength)
              {
  var field = inputText.value;
  var mnlen = minlength;
  var mxlen = maxlength;
  var Errspan = inputText.name + 'Error';

  if (field.length < mnlen || field.length > mxlen)
  {
    document.getElementById(Errspan).innerHTML ="<i class='fas fa-exclamation-circle error-icon'></i>"+ <?php echo  '"'.$lang['error1']. '"'; ?>  + mnlen + ' , ' + mxlen + ' ';
    return false;
  } else
  {
    document.getElementById(Errspan).innerHTML='';
    return true;
  }
}

function preventSpace(inputText, minSpace, maxSpace)
             {
  var field = inputText.value;
  var mnChar = minSpace;
  var mxChar = maxSpace;
  var Errspan = inputText.name + 'Error';

  if (field.split(' ').length - 1 >= 1 && mnChar == 0)
   {
    document.getElementById(Errspan).innerHTML ="<i class='fas fa-exclamation-circle error-icon'></i>"+ <?php echo  '"'.$lang['error4']. '"'; ?> ;
    return false;
  } else if (field.split(' ').length - 1 < mnChar || field.split(' ').length - 1 > mxChar)
  {
    document.getElementById(Errspan).innerHTML ="<i class='fas fa-exclamation-circle error-icon'></i>"+ <?php echo  '"'.$lang['error2']. ' "'; ?> + mnChar + ' , ' + mxChar + ' ';
    return false;
  } else
  {
    document.getElementById(Errspan).innerHTML='';
    return true;
  }
}

function allLetter(inputText)
              {
  var letters = /^[A-Za-z]+$/;
  var Errspan = inputText.name + 'Error';

  if (inputText.value.match(letters))
  {
    document.getElementById(Errspan).innerHTML='';
      return true;
  } else
  {
    document.getElementById(Errspan).innerHTML ="<i class='fas fa-exclamation-circle error-icon'></i>"+ <?php echo  '"'.$lang['error5']. '"'; ?> ;

      return false;
  }
}

                function Requirevalidation(inputText)
                {

  var empt =inputText.value;
  var Errspan = inputText.name + 'Error';

  if (empt == '')
  {
      document.getElementById(Errspan).innerHTML ="<i class='fas fa-exclamation-circle error-icon'></i>"+  <?php echo  '"'.$lang['error3']. '"'; ?>;
      return false;
  } else
  {
    document.getElementById(Errspan).innerHTML='';
      return true;
  }


                }
   function ValidateEmail(inputText)
                {
                var mailformat = /^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/;
                var Errspan = inputText.name + 'Error';


                if(inputText.value.match(mailformat))
                {
                  document.getElementById(Errspan).innerHTML='';
                  return true;
                }
                else
                {
                    document.getElementById(Errspan).innerHTML="<i class='fas fa-exclamation-circle error-icon'></i>"+<?php echo  '"'.$lang['error6'].'"'; ?>;
                    return false;
                }
                }
    function phonenumber(inputText)
                {
                  var Errspan=inputText.name+'Error';

                  var phoneno =/^\+(?:[0-9] ?){6,14}[0-9]$/;
                  if(inputText.value.match(phoneno))
                     {
                      document.getElementById(Errspan).innerHTML='';

                     return true;
                   }
                   else
                     {
                      document.getElementById(Errspan).innerHTML="<i class='fas fa-exclamation-circle error-icon'></i>"+ <?php echo  '"'.$lang['error7'].'"'; ?>;
                      return false;
                     }
                }


   function confirmPassValidation(cpass,opass){

                    var Errspan=cpass.name+'Error';
                    var pass =opass.value.slice(0,cpass.value.length);

                    if (cpass.value!=pass) {
                        document.getElementById(Errspan).innerHTML="<i class='fas fa-exclamation-circle error-icon'></i>"+ <?php echo  '"'.$lang['error8']. '"'; ?>;
                        return false;
                    }
                    else
                    {
                      document.getElementById(Errspan).innerHTML='';
                         return true;
                    }
				}
function validateDate(inputText){
  var Errspan=inputText.name+'Error';

  var CurrentDate = new Date();
  var GivenDate = new Date(inputText.value);

      if(GivenDate < CurrentDate){
              document.getElementById(Errspan).innerHTML="<i class='fas fa-exclamation-circle error-icon'></i>"+ <?php echo '"'.$lang['error9'].'"'; ?> ;
              return false;
          }
          else
          {
            document.getElementById(Errspan).innerHTML='';
               return true;
          }
}
//live search
jQuery_1_3_2(document).ready(function () {
    jQuery_1_3_2('.search-box input[type="text"]').on('keyup input', function () {

        /* Get input value on change */
        var term = jQuery_1_3_2(this).val();

        var resultDropdown = jQuery_1_3_2(this).siblings('.result');
        if (term.length) {
          jQuery_1_3_2.get('/search/livesearch/'+term).done(function (data) {
              // Display the returned data in browser

              resultDropdown.html(data);
            });
        } else {
          resultDropdown.empty();
        }
      });

    // Set search input value on click of result item
    jQuery_1_3_2(document).on('click', '.result p', function () {
        jQuery_1_3_2(this).parents('.search-box').find('input[type="text"]').val(jQuery_1_3_2(this).text().replace(/\s/g, '')).focus();
        jQuery_1_3_2(this).parent('.result').empty();
      });
  });


</script>

</body>
</html>
