<!-- footer start -->
<footer class="footer bg-blue">
<div class="pt-5 footer">
<div class="container">
  <div class="row">
    <div class="col-lg-8 text-left col-xs-12 about-company">
      <img src="/images/home/logo.png" alt="" srcset="">
      <!-- <h2>Fund Me</h2> -->
      <p class="text-white-62"><i class="fas fa-map-marker-alt  mr-3"></i><?php echo $lang ['location'] ?></p>
      <p class="text-white-62"><i class="fas fa-phone mr-3"></i>(541) 754-3010</p>
      <p class="text-white-62"><i class="fas fa-envelope mr-3"></i>info@hsdf.com</p>
    </div>
    <div class="col-lg-4 col-xs-12 location text-center mt-3"> 
    <!-- <h2>Follow Us</h2> -->

      <a href="#" class="fab fa-facebook-f fa-sm"></a>
      <a href="#" class="fab fa-twitter fa-sm"></a>
      <a href="#" class="fab fa-youtube fa-sm"></a>
      <a href="#" class="fab fa-instagram fa-sm"></a>
    </div>
  </div>
  <div class="row mt-5">
    <div class="col copyright text-center">
      <p class=""><small class="text-white-50">© 2020. <a href="#" class="text-white">fundme.com</a></small></p>
    </div>
  </div>
</div>
</div>
</footer>
	<!-- footer end -->