<!-- footer start -->
<footer class="footer text-center bg-blue">
	<p><a href="/home/index" class="text-white" target="_blank">&copy; 2020 foundme.com</a></p>
</footer>
  <!-- footer end -->
  <script src="/js/home/jquery.toast.js"></script>
<script type="text/javascript">
var jQuery_toast = $.noConflict(true);
</script>
<script src="/js/home/js.js"></script>
<script src="/js/home/popper.min.js"></script>
<script src="/js/home/bootstrap.min.js"></script>
<script src="/js/home/wow.min.js"></script>
<script src="/js/home/main.js"></script>

	<script>
	new WOW().init();
	jQuery_1_3_2(document).ready(function(){
         load_notification();
         errMsg('kkk');
  });

  setInterval(function(){
    load_notification();
             }, 10000);

	function load_notification(){
    jQuery_1_3_2.ajax({
 			url:"/notification",
 			method:"POST",
       data:{method:"user"},
 			success:function(data)
 			{
         var notiInfo=JSON.parse(data);
         var html='';
         i=1;
         jQuery_1_3_2('.noti-count').text(notiInfo.count);
         jQuery_1_3_2.each(notiInfo.noti, function( index, row ) {
           if(i<4){

          html+=' <li class="notification-box">'+
                         '<div class="row">'+
                          ' <div class="col-lg-2 col-sm-3 col-3 text-center">'+
                          ' <i class="fa fa-user-circle noti-icon"  aria-hidden="true"></i>'+
                          ' </div>'+
                          ' <div class="col-lg-10 col-sm-8 col-8">'+

                             '<strong class="noti-date">'+row.created_at+'</strong><br>'+

                            '<strong>'+row.type+'</strong><br>'+row.text+
                            ' </div>'+
                          ' </div>    '+
                        ' </div>'+
                      ' </li>';
           }

           i++;
         });
         if(i==1){
          html+=' <li class="notification-box">'+
                         '<div class="row p-5">'+
                         'There is not any notification'
                        ' </div>'+
                      ' </li>';
         }
         else{
          html+='<li class="footer text-center">'+
                                   '<a href="/notification/viewNotification" class="text-blue">View All</a>'+
                               '</li>';
         }
         jQuery_1_3_2('#noti-body').html(html);
       }


 		       });
 }
function converLanguage(lang,dir){

  jQuery_1_3_2.ajax({
 			url:"/language",
 			method:"POST",
       data:{method:"convertLang",lang:lang,dir:dir},
 			success:function(data)
 			{
        var result=JSON.parse(data);

         if(result.statusCode==200){
            setTimeout(function(){
                location. reload();
            }, 2000);
        }

       }
  });

}

	function errMsg(msg){
        if(msg!=''){
          jQuery_toast.toast({
        text: msg, // Text that is to be shown in the toast
        heading: 'Note', // Optional heading to be shown on the toast
        icon: 'info', // Type of toast icon
        showHideTransition: 'fade', // fade, slide or plain
        allowToastClose: true, // Boolean value true or false
        hideAfter: 6000, // false to make it sticky or number representing the miliseconds as time after which toast needs to be hidden
        stack: 5, // false if there should be only one toast at a time or a number representing the maximum number of toasts to be shown at a time
        position: 'bottom-right', // bottom-left or bottom-right or bottom-center or top-left or top-right or top-center or mid-center or an object representing the left, right, top, bottom values



        textAlign: 'left',  // Text alignment i.e. left, right or center
        loader: true,  // Whether to show loader or not. True by default
        loaderBg: '#ffffff',  // Background color of the toast loader
        beforeShow: function () {}, // will be triggered before the toast is shown
        afterShown: function () {}, // will be triggered after the toat has been shown
        beforeHide: function () {}, // will be triggered before the toast gets hidden
        afterHidden: function () {}  // will be triggered after the toast has been hidden
    });
        }
}
errMsg(<?php echo'"'.Message::check('main').'"'; ?>);
//live search
jQuery_1_3_2(document).ready(function () {
    jQuery_1_3_2('.search-box input[type="text"]').on('keyup input', function () {

        /* Get input value on change */
        var term = jQuery_1_3_2(this).val();
				
        var resultDropdown = jQuery_1_3_2(this).siblings('.result');
        if (term.length) {
          jQuery_1_3_2.get('/search/livesearch/'+term).done(function (data) {
              // Display the returned data in browser

              resultDropdown.html(data);
            });
        } else {
          resultDropdown.empty();
        }
      });

    // Set search input value on click of result item
    jQuery_1_3_2(document).on('click', '.result p', function () {
        jQuery_1_3_2(this).parents('.search-box').find('input[type="text"]').val(jQuery_1_3_2(this).text()).focus();
        jQuery_1_3_2(this).parent('.result').empty();
      });
  });


	</script>

</body>
</html>
