<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="/css/home/all.css">
    <link rel="stylesheet" href="/css/home/bootstrap.min.css">
    <link rel="stylesheet" href="/css/home/animate.css">
    <link rel="stylesheet" href="/css/home/style.css">
    <link href="/css/home/jquery.toast.css"  rel="stylesheet">
    <link rel="shortcut icon" type="/image/icon" href="/images/home/logo.png" />
    <script src="/js/home/jquery-3.4.1.slim.min.js"></script>

    <script src="/js/home/validation.js"></script>
    <script class="jsbin" src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
    <script class="jsbin" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.0/jquery-ui.min.js"></script>
    <script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
    <!-- <script src="https://code.jquery.com/jquery-1.11.3.js"></script> -->
    <script type="text/javascript" src="/js/home/tinymce/jquery.tinymce.min.js"></script>
    <script type="text/javascript" src="/js/home/tinymce/tinymce.min.js"></script>

    <script>
        tinymce.init({
          selector : '#mytextarea',
          plugins : 'image',
          toolbar : 'image',

          images_upload_url :'/tiny',
          automatic_uploads : false,

          images_upload_handler : function(blobInfo, success, failure) {
            var xhr, formData;

            xhr = new XMLHttpRequest();
            xhr.withCredentials = false;
            xhr.open('POST','/tiny');

            xhr.onload = function() {
              var json;

              if (xhr.status != 200) {
                failure('HTTP Error: ' + xhr.status);
                return;
              }

              json = JSON.parse(xhr.responseText);

              if (!json || typeof json.file_path != 'string') {
                failure('Invalid JSON: ' + xhr.responseText);
                return;
              }

              success(json.file_path);
            };

            formData = new FormData();
            formData.append('file', blobInfo.blob(), blobInfo.filename());

            xhr.send(formData);
          },
        });


      </script>

    <title> <?php echo  $this->pageTitle; ?></title>
</head>
<body>
