<?php include VIEW.'layouts'.DIRECTORY_SEPARATOR.'head.phtml'; ?>
<!-- Modals -->
<!-- Modal search start -->

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
       
        <div class="modal-body">
            <div class="form-group">
                <input type="text" class="form-control" placeholder="First Name *" value="" />
              </div>
        </div>
        
      </div>
    </div>
  </div>
<!-- Modal search end-->


    <!-- start header -->
    <header>
            <nav class="navbar navbar-expand-lg navbar-top chang-color">
                    <a class="navbar-brand" href="#">
                        <img src="/images/home/logo.png" width="60" height="60" class="d-inline-block align-top" alt="">
                      
                    </a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                      <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse justify-content-center order-2" id="navbarSupportedContent">
                      <ul class="navbar-nav mr-auto a-link">
                        <li class="nav-item active">
                          <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="#">Link</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="/auth/signup">Sing Up</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="/auth/login">LogIn</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="#"  data-toggle="modal" data-target="#exampleModal">Search</a>
                        </li>
                       

                        <li class="nav-item dropdown right-menu">
                          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-camera"></i>THURAYA</a>
                          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="profile.html">My Profile</a>
                            <a class="dropdown-item" href="#">Another action</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">Something else here</a>
                          </div>
                        </li>
                        <!-- <li class="nav-item dropdown right-menu">
                            <button type="button" class="btn btn-white">Start</button>
                        </li> -->

                      </ul>
                    </div>
            </nav>
    </header>
    <!-- end header -->

    <?php echo Message::check('main');  ?>
