
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="shortcut icon" type="/image/icon" class='logoo' href="/images/home/logo.png" />
    <title> <?php echo  $this->pageTitle; ?></title>
    <?php
  if(!array_key_exists('lang',$_COOKIE)){
    setcookie('lang','en-lang', time() + (86400 * 30), "/");
    setcookie('dir', 'ltr', time() + (86400 * 30), "/");
  }
  else{
  ?>
<?php require ROOT.'public'.DIRECTORY_SEPARATOR.'lang'.DIRECTORY_SEPARATOR.$_COOKIE['lang'].'.php'; ?>
    <link rel="stylesheet" href="/css/home/all.css">
    <link rel="stylesheet" href="/css/home/bootstrap-<?php echo $_COOKIE['dir']; ?>.css">
    <link rel="stylesheet" href="/css/home/animate.css">
    <link rel="stylesheet" href="/css/home/style-<?php echo $_COOKIE['dir']; ?>.css">
    <link rel="stylesheet" href="/css/home/new-<?php echo $_COOKIE['dir']; ?>.css">

    <link href="/css/home/jquery.toast.css"  rel="stylesheet">
    <?php } ?>
    <script class="jsbin" src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
    <script src="/js/home/bootstrap.min.js"></script>
    <script src="/js/home/popper.min.js"></script>
    <script src="/js/home/jquery-3.4.1.slim.min.js"></script>
    <script class="jsbin" src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
    <script type="text/javascript">
      var jQuery_1_3_2 = $.noConflict(true);
    </script>
    <!-- <script class="jsbin" src="/js/home/jquery-ui.min.js"></script> -->
    <script src="/js/home/tinymce.min.js" referrerpolicy="origin"></script>
    <script type="text/javascript" src="/js/home/tinymce/jquery.tinymce.min.js"></script>
    <script type="text/javascript" src="/js/home/tinymce/tinymce.min.js"></script>
    <script type="text/javascript" src="/js/home/jquery.min.js"></script> 
    <script type="text/javascript" src="/js/home/tiny.js"></script> 
  
  <?php require VIEW.'layouts'.DIRECTORY_SEPARATOR.'notifications.phtml'; ?>
</head>
<body>
